CREATE TABLE [dbo].[BCP_TEST_SELCOLS] (
    [POLICY_UNDERWRITER]    VARCHAR (3)     NOT NULL,
    [GROUP_NUMBER]          VARCHAR (3)     NOT NULL,
    [CLAIM_NUMBER]          VARCHAR (11)    NOT NULL,
    [PATIENT_DATE_OF_BIRTH] DATE            NULL,
    [ADJUSTMENT_AMOUNT_1]   DECIMAL (11, 2) NULL
);

