CREATE TABLE [dbo].[ELDOMCSCLMLINES] (
    [CLAIM_NO         ]         VARCHAR (50) NULL,
    [LINE_NO]                   VARCHAR (50) NULL,
    [DUP_CLAIM_NO]              VARCHAR (50) NULL,
    [REVENUE_CODE]              VARCHAR (50) NULL,
    [DESCRIPTION]               VARCHAR (50) NULL,
    [HCPCS_PROCEDURE]           VARCHAR (50) NULL,
    [MODIFIER]                  VARCHAR (50) NULL,
    [RATE]                      VARCHAR (50) NULL,
    [DATE_FROM ]                VARCHAR (50) NULL,
    [DATE_TO   ]                VARCHAR (50) NULL,
    [PLACE_OD_SERVICE]          VARCHAR (50) NULL,
    [TYPE_OF_SERVICE]           VARCHAR (50) NULL,
    [UNITS]                     VARCHAR (50) NULL,
    [CHARGE_AMT]                VARCHAR (50) NULL,
    [NON_COVERED]               VARCHAR (50) NULL,
    [DIAG_POINTER]              VARCHAR (50) NULL,
    [EPSDT_FAMILY_PLAN]         VARCHAR (50) NULL,
    [EMG]                       VARCHAR (50) NULL,
    [COB]                       VARCHAR (50) NULL,
    [RESERVED_LOCAL_USE]        VARCHAR (50) NULL,
    [WORKERS_COMP_FEE]          VARCHAR (50) NULL,
    [FEE_SCHEDULE]              VARCHAR (50) NULL,
    [OCN_PRICING_RESULTS]       VARCHAR (50) NULL,
    [DUPL_STATUS]               VARCHAR (50) NULL,
    [MESSAGE_CODE]              VARCHAR (50) NULL,
    [ADJUST_REASON]             VARCHAR (50) NULL,
    [CAP_ENCOUNTERED_AMT]       VARCHAR (50) NULL,
    [CAP_WITHHELD_AMT]          VARCHAR (50) NULL,
    [INCOMING_SERVICE_LINE_NO]  VARCHAR (50) NULL,
    [BENEFIT_CODE]              VARCHAR (50) NULL,
    [TOOTH_NO]                  VARCHAR (50) NULL,
    [TOOTH_SURFACCE]            VARCHAR (50) NULL,
    [TOOTH_SERVICE]             VARCHAR (50) NULL,
    [CHGS]                      VARCHAR (50) NULL,
    [CAP_WITHHELD_PERC]         VARCHAR (50) NULL,
    [CAP_WITHHELD_CODE]         VARCHAR (50) NULL,
    [UB92_UNITS]                VARCHAR (50) NULL,
    [ANESTHESIA_MINUTES]        VARCHAR (50) NULL,
    [DENIED_REASON_CODE]        VARCHAR (50) NULL,
    [POLICY_UNDERWRITER]        VARCHAR (50) NULL,
    [GROUP_NUMBER]              VARCHAR (50) NULL,
    [RPCSD_DAYS]                VARCHAR (50) NULL,
    [ANES_BASE_UNITS]           VARCHAR (50) NULL,
    [MSORDER]                   VARCHAR (50) NULL,
    [REASON_CODE_TO_HPAC]       VARCHAR (50) NULL,
    [UB92V5_RECORD_TYPE]        VARCHAR (50) NULL,
    [OTHER_INSURANCE_PAID]      VARCHAR (50) NULL,
    [OTHER_INSURANCE_ALLOWABLE] VARCHAR (50) NULL,
    [OTHER_INSURANCE_DISCOUNT]  VARCHAR (50) NULL,
    [BUNDLED_FOR_CES_EDITS]     VARCHAR (50) NULL,
    [RPCSLINE_SORTEDITS]        VARCHAR (50) NULL,
    [LOAD_DATE ]                VARCHAR (50) NULL,
    [RPCSSDRATE2]               VARCHAR (50) NULL,
    [OTHER_INSURANCE]           VARCHAR (50) NULL,
    [BCBS_DENY_CODE]            VARCHAR (50) NULL,
    [DISCOUNT]                  VARCHAR (50) NULL,
    [DISCOUNT_CODE]             VARCHAR (50) NULL,
    [COPAY]                     VARCHAR (50) NULL,
    [CARRIER_PAID]              VARCHAR (50) NULL,
    [CARRIER_DENIED]            VARCHAR (50) NULL,
    [GROUPED]                   VARCHAR (50) NULL,
    [LINE_NUMBER]               VARCHAR (50) NULL,
    [UNITS2]                    VARCHAR (50) NULL,
    [DIAG_POINTER2]             VARCHAR (50) NULL,
    [POST_PRICING_FLAG]         VARCHAR (50) NULL
);

