CREATE TABLE [dbo].[ELDOMCSCLAIMS] (
    [MCS_CLAIM_NUMBER ]                                                                                                     VARCHAR (50)  NULL,
    [BATCH_NO]                                                                                                              VARCHAR (50)  NULL,
    [CLAIM]                                                                                                                 VARCHAR (50)  NULL,
    [ADJ_NO]                                                                                                                VARCHAR (50)  NULL,
    [FORM_TYPE]                                                                                                             VARCHAR (50)  NULL,
    [INTERNAL_ID]                                                                                                           VARCHAR (50)  NULL,
    [CLIENT_GROUP_KEY]                                                                                                      VARCHAR (50)  NULL,
    [PROVIDER_KEY]                                                                                                          VARCHAR (50)  NULL,
    [PATIENT_KEY]                                                                                                           VARCHAR (50)  NULL,
    [CLIENT]                                                                                                                VARCHAR (50)  NULL,
    [SVC_GRP_1]                                                                                                             VARCHAR (50)  NULL,
    [SVC_GRP_2]                                                                                                             VARCHAR (50)  NULL,
    [SVC_GRP_3]                                                                                                             VARCHAR (50)  NULL,
    [PO_BOX]                                                                                                                VARCHAR (50)  NULL,
    [CLAIM_NO]                                                                                                              VARCHAR (50)  NULL,
    [PROV_OFFICE                        ]                                                                                   VARCHAR (60)  NULL,
    [PROV_LAST_NAME     ]                                                                                                   VARCHAR (50)  NULL,
    [PROV_FIRST]                                                                                                            VARCHAR (50)  NULL,
    [PROV_MI]                                                                                                               VARCHAR (50)  NULL,
    [PROV_DEG]                                                                                                              VARCHAR (50)  NULL,
    [PROV_ADDRESS1                 ]                                                                                        VARCHAR (50)  NULL,
    [PROV_ADDRESS2]                                                                                                         VARCHAR (50)  NULL,
    [PROV_CITY       ]                                                                                                      VARCHAR (50)  NULL,
    [PROV_STATE]                                                                                                            VARCHAR (50)  NULL,
    [PROV_ZIP ]                                                                                                             VARCHAR (50)  NULL,
    [PROV_COUNTRY]                                                                                                          VARCHAR (50)  NULL,
    [PROV_PHONE]                                                                                                            VARCHAR (50)  NULL,
    [UNUSED]                                                                                                                VARCHAR (50)  NULL,
    [PAT_CTRL           ]                                                                                                   VARCHAR (50)  NULL,
    [TYPE]                                                                                                                  VARCHAR (50)  NULL,
    [FED_TAX  ]                                                                                                             VARCHAR (50)  NULL,
    [FROM_DATE ]                                                                                                            VARCHAR (50)  NULL,
    [THRU_DATE ]                                                                                                            VARCHAR (50)  NULL,
    [COV_D]                                                                                                                 VARCHAR (50)  NULL,
    [N_CD]                                                                                                                  VARCHAR (50)  NULL,
    [C_ID]                                                                                                                  VARCHAR (50)  NULL,
    [L_RD]                                                                                                                  VARCHAR (50)  NULL,
    [UNLABELED]                                                                                                             VARCHAR (50)  NULL,
    [LAST_NAME      ]                                                                                                       VARCHAR (50)  NULL,
    [FIRST_NAME]                                                                                                            VARCHAR (50)  NULL,
    [MI ]                                                                                                                   VARCHAR (50)  NULL,
    [ADDRESS1                   ]                                                                                           VARCHAR (50)  NULL,
    [ADDRESS2               ]                                                                                               VARCHAR (50)  NULL,
    [CITY            ]                                                                                                      VARCHAR (50)  NULL,
    [STATE]                                                                                                                 VARCHAR (50)  NULL,
    [ZIP      ]                                                                                                             VARCHAR (50)  NULL,
    [COUNTRY]                                                                                                               VARCHAR (50)  NULL,
    [DOB       ]                                                                                                            VARCHAR (50)  NULL,
    [SEX]                                                                                                                   VARCHAR (50)  NULL,
    [MARRIED]                                                                                                               VARCHAR (50)  NULL,
    [ADMIT_DATE]                                                                                                            VARCHAR (50)  NULL,
    [ADMIT_HOUR]                                                                                                            VARCHAR (50)  NULL,
    [ADMIT_TYPE]                                                                                                            VARCHAR (50)  NULL,
    [ADMIT_SRC]                                                                                                             VARCHAR (50)  NULL,
    [D_HR]                                                                                                                  VARCHAR (50)  NULL,
    [STAT]                                                                                                                  VARCHAR (50)  NULL,
    [MED_REC_NO       ]                                                                                                     VARCHAR (50)  NULL,
    [COND]                                                                                                                  VARCHAR (50)  NULL,
    [COND_CODE1]                                                                                                            VARCHAR (50)  NULL,
    [COND_CODE2]                                                                                                            VARCHAR (50)  NULL,
    [COND_CODE3]                                                                                                            VARCHAR (50)  NULL,
    [COND_CODE4]                                                                                                            VARCHAR (50)  NULL,
    [COND_CODE5]                                                                                                            VARCHAR (50)  NULL,
    [COND_CODE6]                                                                                                            VARCHAR (50)  NULL,
    [OCCUR_CODE1]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE1]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE2]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE2]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE3]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE3]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE4]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE4]                                                                                                           VARCHAR (50)  NULL,
    [SPAN_CODE1]                                                                                                            VARCHAR (50)  NULL,
    [SPAN_FROM1]                                                                                                            VARCHAR (50)  NULL,
    [SPAN_TO1]                                                                                                              VARCHAR (50)  NULL,
    [OCCUR_CODE5]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE5]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE6]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE6]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE7]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE7]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_CODE8]                                                                                                           VARCHAR (50)  NULL,
    [OCCUR_DATE8]                                                                                                           VARCHAR (50)  NULL,
    [SPAN_CODE2]                                                                                                            VARCHAR (50)  NULL,
    [SPAN_FROM2]                                                                                                            VARCHAR (50)  NULL,
    [SPAN_TO2]                                                                                                              VARCHAR (50)  NULL,
    [A                ]                                                                                                     VARCHAR (50)  NULL,
    [B  ]                                                                                                                   VARCHAR (50)  NULL,
    [C  ]                                                                                                                   VARCHAR (50)  NULL,
    [RSP_LAST_NAME  ]                                                                                                       VARCHAR (50)  NULL,
    [RSP_FIRST ]                                                                                                            VARCHAR (50)  NULL,
    [RSP_MI]                                                                                                                VARCHAR (50)  NULL,
    [RSP_ADDRESS1               ]                                                                                           VARCHAR (50)  NULL,
    [RSP_ADDRESS2           ]                                                                                               VARCHAR (50)  NULL,
    [RSP_CITY        ]                                                                                                      VARCHAR (50)  NULL,
    [RSP_STATE]                                                                                                             VARCHAR (50)  NULL,
    [RSP_ZIP  ]                                                                                                             VARCHAR (50)  NULL,
    [RSP_COUNTRY]                                                                                                           VARCHAR (50)  NULL,
    [RSP_PHONE]                                                                                                             VARCHAR (50)  NULL,
    [CODE1]                                                                                                                 VARCHAR (50)  NULL,
    [AMT1    ]                                                                                                              VARCHAR (50)  NULL,
    [CODE2]                                                                                                                 VARCHAR (50)  NULL,
    [AMT2 ]                                                                                                                 VARCHAR (50)  NULL,
    [CODE3]                                                                                                                 VARCHAR (50)  NULL,
    [AMT3 ]                                                                                                                 VARCHAR (50)  NULL,
    [CODE4]                                                                                                                 VARCHAR (50)  NULL,
    [AMT4 ]                                                                                                                 VARCHAR (50)  NULL,
    [CODE5]                                                                                                                 VARCHAR (50)  NULL,
    [AMT5 ]                                                                                                                 VARCHAR (50)  NULL,
    [CODE6]                                                                                                                 VARCHAR (50)  NULL,
    [AMT6]                                                                                                                  VARCHAR (50)  NULL,
    [CODE7]                                                                                                                 VARCHAR (50)  NULL,
    [AMT7]                                                                                                                  VARCHAR (50)  NULL,
    [CODE8]                                                                                                                 VARCHAR (50)  NULL,
    [AMT8]                                                                                                                  VARCHAR (50)  NULL,
    [CODE9]                                                                                                                 VARCHAR (50)  NULL,
    [AMT9]                                                                                                                  VARCHAR (50)  NULL,
    [CODE10]                                                                                                                VARCHAR (50)  NULL,
    [AMT10]                                                                                                                 VARCHAR (50)  NULL,
    [CODE11]                                                                                                                VARCHAR (50)  NULL,
    [AMT11]                                                                                                                 VARCHAR (50)  NULL,
    [CODE12]                                                                                                                VARCHAR (50)  NULL,
    [AMT12]                                                                                                                 VARCHAR (50)  NULL,
    [PAYER_ID1]                                                                                                             VARCHAR (50)  NULL,
    [SUB_ID1]                                                                                                               VARCHAR (50)  NULL,
    [NAME1             ]                                                                                                    VARCHAR (50)  NULL,
    [PAYER_ID2]                                                                                                             VARCHAR (50)  NULL,
    [SUB_ID2]                                                                                                               VARCHAR (50)  NULL,
    [NAME2             ]                                                                                                    VARCHAR (50)  NULL,
    [PAYER_ID3]                                                                                                             VARCHAR (50)  NULL,
    [SUB_ID3]                                                                                                               VARCHAR (50)  NULL,
    [NAME3             ]                                                                                                    VARCHAR (50)  NULL,
    [PROV_NO1 ]                                                                                                             VARCHAR (50)  NULL,
    [PROV_NO2 ]                                                                                                             VARCHAR (50)  NULL,
    [PROV_NO3]                                                                                                              VARCHAR (50)  NULL,
    [REL_INF1]                                                                                                              VARCHAR (50)  NULL,
    [REL_INF2]                                                                                                              VARCHAR (50)  NULL,
    [REL_INF3]                                                                                                              VARCHAR (50)  NULL,
    [ASG_BEN1]                                                                                                              VARCHAR (50)  NULL,
    [ASG_BEN2]                                                                                                              VARCHAR (50)  NULL,
    [ASG_BEN3]                                                                                                              VARCHAR (50)  NULL,
    [PRIOR_AMOUNT1]                                                                                                         VARCHAR (50)  NULL,
    [PRIOR_AMOUNT2]                                                                                                         VARCHAR (50)  NULL,
    [PRIOR_AMOUNT3]                                                                                                         VARCHAR (50)  NULL,
    [DUE_FROM_PAT1]                                                                                                         VARCHAR (50)  NULL,
    [EST_DUE1]                                                                                                              VARCHAR (50)  NULL,
    [EST_DUE2]                                                                                                              VARCHAR (50)  NULL,
    [EST_DUE3]                                                                                                              VARCHAR (50)  NULL,
    [DUE_FROM_PAT2]                                                                                                         VARCHAR (50)  NULL,
    [INSURED1       ]                                                                                                       VARCHAR (50)  NULL,
    [INSURED1_BLANK1]                                                                                                       VARCHAR (50)  NULL,
    [INSURED1_BLANK2]                                                                                                       VARCHAR (50)  NULL,
    [INSURED2  ]                                                                                                            VARCHAR (50)  NULL,
    [INSURED2_BLANK1]                                                                                                       VARCHAR (50)  NULL,
    [INSURED2_BLANK2]                                                                                                       VARCHAR (50)  NULL,
    [INSURED3]                                                                                                              VARCHAR (50)  NULL,
    [INSURED3_BLANK1]                                                                                                       VARCHAR (50)  NULL,
    [INSURED3_BLANK2]                                                                                                       VARCHAR (50)  NULL,
    [PAT_REL1]                                                                                                              VARCHAR (50)  NULL,
    [PAT_REL2]                                                                                                              VARCHAR (50)  NULL,
    [PAT_REL3]                                                                                                              VARCHAR (50)  NULL,
    [CERT_SSN_HIC_ID1]                                                                                                      VARCHAR (50)  NULL,
    [CERT_SSN_HIC_ID2]                                                                                                      VARCHAR (50)  NULL,
    [CERT_SSN_HIC_ID3]                                                                                                      VARCHAR (50)  NULL,
    [GROUP_NAME1   ]                                                                                                        VARCHAR (50)  NULL,
    [GROUP_NAME2]                                                                                                           VARCHAR (50)  NULL,
    [GROUP_NAME3]                                                                                                           VARCHAR (50)  NULL,
    [GROUP_NUMBER1]                                                                                                         VARCHAR (50)  NULL,
    [GROUP_NUMBER2]                                                                                                         VARCHAR (50)  NULL,
    [GROUP_NUMBER3]                                                                                                         VARCHAR (50)  NULL,
    [TREAT_CODES1]                                                                                                          VARCHAR (50)  NULL,
    [TREAT_CODES2]                                                                                                          VARCHAR (50)  NULL,
    [TREAT_CODES3]                                                                                                          VARCHAR (50)  NULL,
    [ESC1]                                                                                                                  VARCHAR (50)  NULL,
    [ESC2]                                                                                                                  VARCHAR (50)  NULL,
    [ESC3]                                                                                                                  VARCHAR (50)  NULL,
    [EMPLOYER_NAME1]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_NAME2]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_NAME3]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_ADDRESS1]                                                                                                     VARCHAR (50)  NULL,
    [EMPLOYER_CITY1]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_STATE1]                                                                                                       VARCHAR (50)  NULL,
    [EMPLOYER_ZIP1]                                                                                                         VARCHAR (50)  NULL,
    [EMPLOYER_COUNTRY1]                                                                                                     VARCHAR (50)  NULL,
    [EMPLOYER_ADDRESS2]                                                                                                     VARCHAR (50)  NULL,
    [EMPLOYER_CITY2]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_STATE2]                                                                                                       VARCHAR (50)  NULL,
    [EMPLOYER_ZIP2]                                                                                                         VARCHAR (50)  NULL,
    [EMPLOYER_COUNTRY2]                                                                                                     VARCHAR (50)  NULL,
    [EMPLOYER_ADDRESS3]                                                                                                     VARCHAR (50)  NULL,
    [EMPLOYER_CITY3]                                                                                                        VARCHAR (50)  NULL,
    [EMPLOYER_STATE3]                                                                                                       VARCHAR (50)  NULL,
    [EMPLOYER_ZIP3]                                                                                                         VARCHAR (50)  NULL,
    [COUNTRY3]                                                                                                              VARCHAR (50)  NULL,
    [PRINC_DIAG1]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG1]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG2]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG3]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG4]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG5]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG6]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG7]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG8]                                                                                                           VARCHAR (50)  NULL,
    [ADMIT_DIAG]                                                                                                            VARCHAR (50)  NULL,
    [E_CODE]                                                                                                                VARCHAR (50)  NULL,
    [PC ]                                                                                                                   VARCHAR (50)  NULL,
    [PRINC_PROC]                                                                                                            VARCHAR (50)  NULL,
    [PRINC_PROC_DATE]                                                                                                       VARCHAR (50)  NULL,
    [OTHER_PROC1]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_PROC_DATE1]                                                                                                      VARCHAR (50)  NULL,
    [OTHER_PROC2]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_PROC_DATE2]                                                                                                      VARCHAR (50)  NULL,
    [OTHER_PROC3]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_PROC_DATE3]                                                                                                      VARCHAR (50)  NULL,
    [OTHER_PROC4]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_PROC_DATE4]                                                                                                      VARCHAR (50)  NULL,
    [OTHER_PROC5]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_PROC_DATE5]                                                                                                      VARCHAR (50)  NULL,
    [ATTENDING_PHYSICIAN]                                                                                                   VARCHAR (50)  NULL,
    [ATT_PHY_LAST_NAME]                                                                                                     VARCHAR (50)  NULL,
    [ATT_PHY_FIRST_NAME]                                                                                                    VARCHAR (50)  NULL,
    [ATT_PHY_MIDDLE]                                                                                                        VARCHAR (50)  NULL,
    [ATT_PHY_DEGREE]                                                                                                        VARCHAR (50)  NULL,
    [OTHER_PHY1]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_PHY1_LAST_NAME]                                                                                                  VARCHAR (50)  NULL,
    [OTHER_PHY1_FIRST_NAME]                                                                                                 VARCHAR (50)  NULL,
    [OTHER_PHY1_MIDDLE]                                                                                                     VARCHAR (50)  NULL,
    [OTHER_PHY1_DEGREE]                                                                                                     VARCHAR (50)  NULL,
    [OTHER_PHY2]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_PHY2_LAST_NAME]                                                                                                  VARCHAR (50)  NULL,
    [OTHER_PHY2_FIRST_NAME]                                                                                                 VARCHAR (50)  NULL,
    [OTHER_PHY2_MIDDLE]                                                                                                     VARCHAR (50)  NULL,
    [OTHER_PHY2_DEGREE]                                                                                                     VARCHAR (50)  NULL,
    [REMARKS1]                                                                                                              VARCHAR (50)  NULL,
    [REMARKS2]                                                                                                              VARCHAR (50)  NULL,
    [REMARKS3]                                                                                                              VARCHAR (50)  NULL,
    [REMARKS4]                                                                                                              VARCHAR (50)  NULL,
    [SIGNATURE1]                                                                                                            VARCHAR (50)  NULL,
    [DATE_SIGNED1]                                                                                                          VARCHAR (50)  NULL,
    [COVERAGE_TYPE]                                                                                                         VARCHAR (50)  NULL,
    [PHONE_PATIENT]                                                                                                         VARCHAR (50)  NULL,
    [EMPL_STATUS]                                                                                                           VARCHAR (50)  NULL,
    [EMPLOYMENT]                                                                                                            VARCHAR (50)  NULL,
    [AUTO_ACCID]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_ACCID]                                                                                                           VARCHAR (50)  NULL,
    [PLACE]                                                                                                                 VARCHAR (50)  NULL,
    [OTHER_DOB ]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_SEX]                                                                                                             VARCHAR (50)  NULL,
    [INSUR_DOB ]                                                                                                            VARCHAR (50)  NULL,
    [INSUR_SEX]                                                                                                             VARCHAR (50)  NULL,
    [ANOTHER_PLAN]                                                                                                          VARCHAR (50)  NULL,
    [SIGNATURE2]                                                                                                            VARCHAR (50)  NULL,
    [DATE_SIGNED2]                                                                                                          VARCHAR (50)  NULL,
    [SIGNATURE3]                                                                                                            VARCHAR (50)  NULL,
    [REFER_PHYS]                                                                                                            VARCHAR (50)  NULL,
    [REFER_PHY_ID]                                                                                                          VARCHAR (50)  NULL,
    [OUTSIDE_LAB]                                                                                                           VARCHAR (50)  NULL,
    [LAB_CHARGES]                                                                                                           VARCHAR (50)  NULL,
    [MEDICAID_RESUB]                                                                                                        VARCHAR (50)  NULL,
    [ORIG_REF_NO      ]                                                                                                     VARCHAR (50)  NULL,
    [PRIOR_AUTH]                                                                                                            VARCHAR (50)  NULL,
    [SSN]                                                                                                                   VARCHAR (50)  NULL,
    [ACCEPT_ASSIGN]                                                                                                         VARCHAR (50)  NULL,
    [AMOUNT_PAID]                                                                                                           VARCHAR (50)  NULL,
    [BALANCE_DUE]                                                                                                           VARCHAR (50)  NULL,
    [FACILITY                           ]                                                                                   VARCHAR (MAX) NULL,
    [FACILITY_ADDRESS1               ]                                                                                      VARCHAR (MAX) NULL,
    [FACILITY_ADDRESS2]                                                                                                     VARCHAR (MAX) NULL,
    [FACILITY_CITY  ]                                                                                                       VARCHAR (50)  NULL,
    [FACILITY_STATE]                                                                                                        VARCHAR (50)  NULL,
    [FACILITY_ZIP]                                                                                                          VARCHAR (50)  NULL,
    [FACILITY_COUNTRY]                                                                                                      VARCHAR (50)  NULL,
    [PROV_PIN       ]                                                                                                       VARCHAR (50)  NULL,
    [CLIENT_STATUS]                                                                                                         VARCHAR (50)  NULL,
    [PROVIDER_STATUS]                                                                                                       VARCHAR (50)  NULL,
    [PATIENT_STATUS]                                                                                                        VARCHAR (50)  NULL,
    [CLAIM_STATUS]                                                                                                          VARCHAR (50)  NULL,
    [ORIG_STATUS]                                                                                                           VARCHAR (50)  NULL,
    [ACTION_FLAG]                                                                                                           VARCHAR (50)  NULL,
    [DRG_CODE]                                                                                                              VARCHAR (50)  NULL,
    [DRG_AMT]                                                                                                               VARCHAR (50)  NULL,
    [SUBMITTER_ID]                                                                                                          VARCHAR (50)  NULL,
    [FED_SUB_ID]                                                                                                            VARCHAR (50)  NULL,
    [ATTACH_1]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_2]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_3]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_4]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_5]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_6]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_7]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_8]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_9]                                                                                                              VARCHAR (50)  NULL,
    [ATTACH_10]                                                                                                             VARCHAR (50)  NULL,
    [PAT_SSN  ]                                                                                                             VARCHAR (50)  NULL,
    [MEDICARE_PROV_NO]                                                                                                      VARCHAR (50)  NULL,
    [SERVICE_LINES]                                                                                                         VARCHAR (50)  NULL,
    [WORK_COMP_TOTAL_FEE]                                                                                                   VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT1]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT2]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT3]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT4]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT5]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT6]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT7]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_A_AMOUNT8]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT1]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT2]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT3]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT4]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT5]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT6]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT7]                                                                                                    VARCHAR (50)  NULL,
    [MEDICARE_B_AMOUNT8]                                                                                                    VARCHAR (50)  NULL,
    [COB_OTHER_INS_PAID]                                                                                                    VARCHAR (50)  NULL,
    [COB_OTHER_INS_COINSUR]                                                                                                 VARCHAR (50)  NULL,
    [COB_OTHER_INS_NONCOVERED]                                                                                              VARCHAR (50)  NULL,
    [COB_ALLOWED_AMOUNT]                                                                                                    VARCHAR (50)  NULL,
    [CLIENT_CHARGES]                                                                                                        VARCHAR (50)  NULL,
    [IN_OUT_PATIENT]                                                                                                        VARCHAR (50)  NULL,
    [WC_PERCENT]                                                                                                            VARCHAR (50)  NULL,
    [CONTR_MESSAGE]                                                                                                         VARCHAR (50)  NULL,
    [CONTR_EXCEPT]                                                                                                          VARCHAR (50)  NULL,
    [CONTR_METHOD]                                                                                                          VARCHAR (50)  NULL,
    [RATE_CATEGORY1]                                                                                                        VARCHAR (50)  NULL,
    [RATE_CATEGORY2]                                                                                                        VARCHAR (50)  NULL,
    [RATE_CATEGORY3]                                                                                                        VARCHAR (50)  NULL,
    [TOTAL_CHARGES]                                                                                                         VARCHAR (50)  NULL,
    [PRICING_FLAG]                                                                                                          VARCHAR (50)  NULL,
    [EXCLUDED_AMOUNT]                                                                                                       VARCHAR (50)  NULL,
    [REVISED_CHARGES]                                                                                                       VARCHAR (50)  NULL,
    [NEGOTIATED_RATE]                                                                                                       VARCHAR (50)  NULL,
    [PPO_SAVINGS]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_SAVINGS]                                                                                                         VARCHAR (50)  NULL,
    [SAVINGS_CODE]                                                                                                          VARCHAR (50)  NULL,
    [PPO_FEE]                                                                                                               VARCHAR (50)  NULL,
    [PRICING_ACTION]                                                                                                        VARCHAR (50)  NULL,
    [NEXT_COMMAND]                                                                                                          VARCHAR (50)  NULL,
    [PRODUCT_CODE]                                                                                                          VARCHAR (50)  NULL,
    [FORM]                                                                                                                  VARCHAR (50)  NULL,
    [TEMPLATE]                                                                                                              VARCHAR (50)  NULL,
    [TEAM_ASSIGNED]                                                                                                         VARCHAR (50)  NULL,
    [DATE_NEXT_ACTION]                                                                                                      VARCHAR (50)  NULL,
    [DATE_RECEIVED]                                                                                                         VARCHAR (50)  NULL,
    [ADJUST_SOURCE]                                                                                                         VARCHAR (50)  NULL,
    [ADJUST_REASON1]                                                                                                        VARCHAR (50)  NULL,
    [ADJUST_REASON2]                                                                                                        VARCHAR (50)  NULL,
    [ADJUST_REASON3]                                                                                                        VARCHAR (50)  NULL,
    [ADJUST_ACTION]                                                                                                         VARCHAR (50)  NULL,
    [REFER_CLAIM_NUM]                                                                                                       VARCHAR (50)  NULL,
    [BACKOUT_NO_DAYS]                                                                                                       VARCHAR (50)  NULL,
    [BACKOUT_NO_VISITS]                                                                                                     VARCHAR (50)  NULL,
    [BACKOUT_NO_UNITS]                                                                                                      VARCHAR (50)  NULL,
    [BACKOUT_BILLED]                                                                                                        VARCHAR (50)  NULL,
    [BACKOUT_NEGOT]                                                                                                         VARCHAR (50)  NULL,
    [BACKOUT_EXCLUDE]                                                                                                       VARCHAR (50)  NULL,
    [CLIENT_PRODUCT_USED]                                                                                                   VARCHAR (50)  NULL,
    [PROVIDER_CONTR_USED]                                                                                                   VARCHAR (50)  NULL,
    [EPISODE_USED]                                                                                                          VARCHAR (50)  NULL,
    [ENROLLMENT_USED]                                                                                                       VARCHAR (50)  NULL,
    [ADMISSION_AGE]                                                                                                         VARCHAR (50)  NULL,
    [DAYS_IN_HOSPITAL]                                                                                                      VARCHAR (50)  NULL,
    [INVOICE_DATE]                                                                                                          VARCHAR (50)  NULL,
    [ECS_OUTPUT_DATE]                                                                                                       VARCHAR (50)  NULL,
    [HP2_CLAIM_NUMBER]                                                                                                      VARCHAR (50)  NULL,
    [OWNER_OF_RECORD]                                                                                                       VARCHAR (50)  NULL,
    [CHARGE_TYPE]                                                                                                           VARCHAR (50)  NULL,
    [PAYMENT_TYPE]                                                                                                          VARCHAR (50)  NULL,
    [ECS_STATUS]                                                                                                            VARCHAR (50)  NULL,
    [USER_FILE_STATUS]                                                                                                      VARCHAR (50)  NULL,
    [PRINT_STATUS]                                                                                                          VARCHAR (50)  NULL,
    [INVESTIGATIVE_PROC]                                                                                                    VARCHAR (50)  NULL,
    [COSMETIC_SURGERY]                                                                                                      VARCHAR (50)  NULL,
    [ELECTIVE_SURGERY]                                                                                                      VARCHAR (50)  NULL,
    [PRIOR_APPROVAL_REQ]                                                                                                    VARCHAR (50)  NULL,
    [PRE_EXISTING_COND]                                                                                                     VARCHAR (50)  NULL,
    [MULTIPLE_CONDITION]                                                                                                    VARCHAR (50)  NULL,
    [EDI_INCOMING_CLAIM_NO]                                                                                                 VARCHAR (50)  NULL,
    [ENCOUNTERED_AMT]                                                                                                       VARCHAR (50)  NULL,
    [WITHHELD_AMT]                                                                                                          VARCHAR (50)  NULL,
    [INTERLINK_DATA]                                                                                                        VARCHAR (50)  NULL,
    [ADJUDICATE_PENALTY]                                                                                                    VARCHAR (50)  NULL,
    [ADJUDICATE_PRECERT]                                                                                                    VARCHAR (50)  NULL,
    [INVOICE_AMOUNT]                                                                                                        VARCHAR (50)  NULL,
    [HP2_POLICY_TYPE]                                                                                                       VARCHAR (50)  NULL,
    [HP2_CLAIM_COUNT]                                                                                                       VARCHAR (50)  NULL,
    [HP_ADJUD]                                                                                                              VARCHAR (50)  NULL,
    [HP_ADJUD_CREATED_DATE]                                                                                                 VARCHAR (50)  NULL,
    [HP_ADJUD_BY1]                                                                                                          VARCHAR (50)  NULL,
    [HP_ADJUD_CHANGED_DATE]                                                                                                 VARCHAR (50)  NULL,
    [HP_ADJUD_BY2]                                                                                                          VARCHAR (50)  NULL,
    [HPAC_UNDERWRITER]                                                                                                      VARCHAR (50)  NULL,
    [HPAC_GROUP]                                                                                                            VARCHAR (50)  NULL,
    [HPAC_DEPENDENT_SEQ_NO]                                                                                                 VARCHAR (50)  NULL,
    [HPAC_DGN_NUMBER]                                                                                                       VARCHAR (50)  NULL,
    [HPAC_PEND_FLAG]                                                                                                        VARCHAR (50)  NULL,
    [HPAC_COVERAGE]                                                                                                         VARCHAR (50)  NULL,
    [HPAC_CLASS]                                                                                                            VARCHAR (50)  NULL,
    [HPAC_PEND_DESCRIPTION]                                                                                                 VARCHAR (50)  NULL,
    [HPAC_PEND_BY_MCS_CODE]                                                                                                 VARCHAR (50)  NULL,
    [PROV_TYPE_FROM_RPV]                                                                                                    VARCHAR (50)  NULL,
    [HPAC_PROVIDER_ID]                                                                                                      VARCHAR (50)  NULL,
    [NEIC_ID]                                                                                                               VARCHAR (50)  NULL,
    [NEIC_SYTEM]                                                                                                            VARCHAR (50)  NULL,
    [REVIEW_DATE]                                                                                                           VARCHAR (50)  NULL,
    [SEND_TO_BWC]                                                                                                           VARCHAR (50)  NULL,
    [FORM_BWC_EOB_CODE]                                                                                                     VARCHAR (50)  NULL,
    [TIFF_IMAGE           ]                                                                                                 VARCHAR (50)  NULL,
    [DRUG_NUMBER]                                                                                                           VARCHAR (50)  NULL,
    [DRUG_DOSAGE_FORM]                                                                                                      VARCHAR (50)  NULL,
    [BWC_ID_PHYSFACIL_BWC_NBR]                                                                                              VARCHAR (50)  NULL,
    [RPRICE_EXCEEDS_CHGS]                                                                                                   VARCHAR (50)  NULL,
    [ATTACH_IND]                                                                                                            VARCHAR (50)  NULL,
    [POLICY_UNDERWRITER]                                                                                                    VARCHAR (50)  NULL,
    [GROUP_NUMBER]                                                                                                          VARCHAR (50)  NULL,
    [CLAIM_NUMBER]                                                                                                          VARCHAR (50)  NULL,
    [COB_OVERRIDE]                                                                                                          VARCHAR (50)  NULL,
    [COB_MEDICARE_CLAIM]                                                                                                    VARCHAR (50)  NULL,
    [PRICING_CONTRACT_USED]                                                                                                 VARCHAR (50)  NULL,
    [PRICING_RULES_FROM]                                                                                                    VARCHAR (50)  NULL,
    [FLAGS_FROM_CLAIM_ADJUSTMENT]                                                                                           VARCHAR (50)  NULL,
    [MOVED_TO_RPCEDIFILLER]                                                                                                 VARCHAR (50)  NULL,
    [EDI_ENTITY]                                                                                                            VARCHAR (50)  NULL,
    [CLAIM_NCPDP]                                                                                                           VARCHAR (50)  NULL,
    [CUT_A_CHECK]                                                                                                           VARCHAR (50)  NULL,
    [VISITS_FOR_EVENT_PROCESSING]                                                                                           VARCHAR (50)  NULL,
    [UNITS_FOR_EVENT_PROCESSING]                                                                                            VARCHAR (50)  NULL,
    [PRE_PRICED_FLAG]                                                                                                       VARCHAR (50)  NULL,
    [EDI_INCOMING_RPC_H12A]                                                                                                 VARCHAR (50)  NULL,
    [EHC_STATUS]                                                                                                            VARCHAR (50)  NULL,
    [EHC_KEY_REMOTE_PRICING]                                                                                                VARCHAR (50)  NULL,
    [PCP_PROVIDER]                                                                                                          VARCHAR (50)  NULL,
    [IPN_TRANSACTION_CTRL]                                                                                                  VARCHAR (50)  NULL,
    [IMAGING_INTERNAL_FLAG]                                                                                                 VARCHAR (50)  NULL,
    [INSURED_SSN_EMP]                                                                                                       VARCHAR (50)  NULL,
    [JULIAN_YEAR]                                                                                                           VARCHAR (50)  NULL,
    [JULIAN_DAY]                                                                                                            VARCHAR (50)  NULL,
    [BATCH_NUMBER]                                                                                                          VARCHAR (50)  NULL,
    [CLAIM_EORM]                                                                                                            VARCHAR (50)  NULL,
    [TYPE_OF_FORM_USED]                                                                                                     VARCHAR (50)  NULL,
    [BENEFIT_PLAN_USED]                                                                                                     VARCHAR (50)  NULL,
    [BENEFIT_PLAN_DATE]                                                                                                     VARCHAR (50)  NULL,
    [OHIO_BWC_EOB_FLAG]                                                                                                     VARCHAR (50)  NULL,
    [MANUAL_WORKFLOW_QUEUE_ASS]                                                                                             VARCHAR (50)  NULL,
    [REPRICERS_ORG_ID]                                                                                                      VARCHAR (50)  NULL,
    [EDI_DATA_EXCEPTION_FLAG]                                                                                               VARCHAR (50)  NULL,
    [ADJ_CLAIM_1]                                                                                                           VARCHAR (50)  NULL,
    [ADJ_CLAIM_2]                                                                                                           VARCHAR (50)  NULL,
    [REFERRAL_FOR_CLAIM]                                                                                                    VARCHAR (50)  NULL,
    [REFERRAL_REMARK]                                                                                                       VARCHAR (50)  NULL,
    [EDI_FILE_NAME                 ]                                                                                        VARCHAR (50)  NULL,
    [RPC_FILLER                                                                                                           ] VARCHAR (MAX) NULL,
    [LOAD_DATE ]                                                                                                            VARCHAR (MAX) NULL,
    [CONDITION_CODE1]                                                                                                       VARCHAR (50)  NULL,
    [CONDITION_CODE2]                                                                                                       VARCHAR (50)  NULL,
    [CONDITION_CODE3]                                                                                                       VARCHAR (50)  NULL,
    [CONDITION_CODE4]                                                                                                       VARCHAR (50)  NULL,
    [ACCIDENT_STATE]                                                                                                        VARCHAR (50)  NULL,
    [ICD9_VERSION]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG9]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_DIAG10]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG11]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG12]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG13]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG14]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG15]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG16]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG17]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG18]                                                                                                          VARCHAR (50)  NULL,
    [OTHER_DIAG19]                                                                                                          VARCHAR (50)  NULL,
    [PATIENT_DIAGNOSIS1]                                                                                                    VARCHAR (50)  NULL,
    [PATIENT_DIAGNOSIS2]                                                                                                    VARCHAR (50)  NULL,
    [PATIENT_DIAGNOSIS3]                                                                                                    VARCHAR (50)  NULL,
    [E_CODE2]                                                                                                               VARCHAR (50)  NULL,
    [E_CODE3]                                                                                                               VARCHAR (50)  NULL,
    [ATTENDING_NPI]                                                                                                         VARCHAR (50)  NULL,
    [ATTENDING_QUAL]                                                                                                        VARCHAR (50)  NULL,
    [OPERATING_NPI]                                                                                                         VARCHAR (50)  NULL,
    [OPERATING_QUAL]                                                                                                        VARCHAR (50)  NULL,
    [OPERATING_PHY]                                                                                                         VARCHAR (50)  NULL,
    [OPERATING_LAST_NAME]                                                                                                   VARCHAR (50)  NULL,
    [OPERATING_FIRST_NAME]                                                                                                  VARCHAR (50)  NULL,
    [OTHER_NPI1]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_QUAL1]                                                                                                           VARCHAR (50)  NULL,
    [OTHER_NPI2]                                                                                                            VARCHAR (50)  NULL,
    [OTHER_QUAL2]                                                                                                           VARCHAR (50)  NULL,
    [QUAL_A]                                                                                                                VARCHAR (50)  NULL,
    [CODE_A]                                                                                                                VARCHAR (50)  NULL,
    [VALUE_A]                                                                                                               VARCHAR (50)  NULL,
    [QUAL_B]                                                                                                                VARCHAR (50)  NULL,
    [CODE_B]                                                                                                                VARCHAR (50)  NULL,
    [VALUE_B]                                                                                                               VARCHAR (50)  NULL,
    [QUAL_C]                                                                                                                VARCHAR (50)  NULL,
    [CODE_C]                                                                                                                VARCHAR (50)  NULL,
    [VALUE_C]                                                                                                               VARCHAR (50)  NULL,
    [QUAL_D]                                                                                                                VARCHAR (50)  NULL,
    [CODE_D]                                                                                                                VARCHAR (50)  NULL,
    [VALUE_D]                                                                                                               VARCHAR (50)  NULL,
    [AMPS_NEGOTIATED_ON_DISCOUNT]                                                                                           VARCHAR (50)  NULL,
    [MAIN_EPISODE]                                                                                                          VARCHAR (50)  NULL,
    [REIMBURSEMENT_TYPE]                                                                                                    VARCHAR (50)  NULL,
    [EXTACTED_TO_COA]                                                                                                       VARCHAR (50)  NULL,
    [LSFA_SELECTED_PROD_MANUAL]                                                                                             VARCHAR (50)  NULL,
    [UB_VERSION]                                                                                                            VARCHAR (50)  NULL,
    [POSTADJ]                                                                                                               VARCHAR (50)  NULL,
    [SENTNTTY]                                                                                                              VARCHAR (50)  NULL,
    [SAVRORGID]                                                                                                             VARCHAR (50)  NULL,
    [PMCS]                                                                                                                  VARCHAR (50)  NULL,
    [INDTYPE]                                                                                                               VARCHAR (50)  NULL,
    [EXSTATUS]                                                                                                              VARCHAR (50)  NULL,
    [B61A                          ]                                                                                        VARCHAR (50)  NULL,
    [B61B]                                                                                                                  VARCHAR (50)  NULL,
    [B61C]                                                                                                                  VARCHAR (50)  NULL,
    [B77P]                                                                                                                  VARCHAR (50)  NULL,
    [B77BP]                                                                                                                 VARCHAR (50)  NULL,
    [B77CP]                                                                                                                 VARCHAR (50)  NULL,
    [POSTADJPQ]                                                                                                             VARCHAR (50)  NULL,
    [OVRDCES]                                                                                                               VARCHAR (50)  NULL,
    [GROUPED]                                                                                                               VARCHAR (50)  NULL,
    [RPC_OVRPTOD]                                                                                                           VARCHAR (50)  NULL,
    [HCFA_NPI]                                                                                                              VARCHAR (50)  NULL,
    [APR_DRUG_CODE]                                                                                                         VARCHAR (50)  NULL,
    [ADDITIONAL_CLAIM_INFO]                                                                                                 VARCHAR (50)  NULL,
    [RESUMISSION_REF_ID]                                                                                                    VARCHAR (50)  NULL,
    [VENDOR_CHECK]                                                                                                          VARCHAR (50)  NULL,
    [EPAY]                                                                                                                  VARCHAR (50)  NULL,
    [DRGWEIGHT]                                                                                                             VARCHAR (50)  NULL
);

