CREATE TABLE [dbo].[ELDOLOADMASTER] (
    [REC_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [JOB_NAM]         VARCHAR (60)   NOT NULL,
    [PROCESS_NAME]    VARCHAR (60)   NOT NULL,
    [PARAMETER]       VARCHAR (60)   NOT NULL,
    [PARAMETER_DESC]  VARCHAR (100)  NOT NULL,
    [PARAMETER_VALUE] VARCHAR (2000) NOT NULL,
    [CREATE_DATE]     DATE           CONSTRAINT [ELDOLOADMASTER_CREATE_DATE] DEFAULT (getdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME       CONSTRAINT [ELDOLOADMASTER_LAST_UPDATE] DEFAULT (getdate()) NOT NULL
);

