CREATE TABLE [dbo].[ELDOEMPLOYEE] (
    [POLICY_UNDERWRITER_NUMBER]                VARCHAR (50) NULL,
    [GROUP_NUMBER]                             VARCHAR (50) NULL,
    [EMPLOYEE_SSN]                             VARCHAR (50) NULL,
    [DATE_LAST_CHANGED]                        VARCHAR (50) NULL,
    [CHANGE_BY]                                VARCHAR (50) NULL,
    [EMPLOYEE_CERTIFICATE_NUMBER]              VARCHAR (50) NULL,
    [EMPLOYEE_LAST_NAME]                       VARCHAR (50) NULL,
    [EMPLOYEE_FIRST_NAME]                      VARCHAR (50) NULL,
    [EMPLOYEE_MIDDLE_INITIAL]                  VARCHAR (50) NULL,
    [EMPLOYEE_NAME_SUFFIX]                     VARCHAR (50) NULL,
    [EMPLOYEE_NAME             ]               VARCHAR (50) NULL,
    [ADDRESS_LINE_1               ]            VARCHAR (50) NULL,
    [ADDRESS_LINE_2         ]                  VARCHAR (50) NULL,
    [CITY           ]                          VARCHAR (50) NULL,
    [STATE]                                    VARCHAR (50) NULL,
    [ZIP_CODE ]                                VARCHAR (50) NULL,
    [PROCEDURE_LOCATION_CODE]                  VARCHAR (50) NULL,
    [HOME_PHONE_NUMBER]                        VARCHAR (50) NULL,
    [WORK_PHONE_NUMBER]                        VARCHAR (50) NULL,
    [DEPARTMENT_NUMBER]                        VARCHAR (50) NULL,
    [SEX]                                      VARCHAR (50) NULL,
    [DATE_OF_BIRTH]                            VARCHAR (50) NULL,
    [HIRED_DATE]                               VARCHAR (50) NULL,
    [DATE_OF_FIRST_ENROLLMENT]                 VARCHAR (50) NULL,
    [LEAVING_REASON]                           VARCHAR (50) NULL,
    [LAST_BILLING_DATE]                        VARCHAR (50) NULL,
    [NUMBER_OF_DEPENDENTS]                     VARCHAR (50) NULL,
    [NUMBER_OF_DEPENDENTS_ON_FILE]             VARCHAR (50) NULL,
    [XTRA_1]                                   VARCHAR (50) NULL,
    [SPECIAL_CODES]                            VARCHAR (50) NULL,
    [NOTES_1                                 ] VARCHAR (50) NULL,
    [NOTES_2                           ]       VARCHAR (50) NULL,
    [BENEFICIARY_NAME             ]            VARCHAR (50) NULL,
    [LIFETIME_PENSION_CREDITS]                 VARCHAR (50) NULL,
    [PENSION_YR_LFTIME_CR]                     VARCHAR (50) NULL,
    [XTRA_2]                                   VARCHAR (50) NULL,
    [PREMIUMS_PAID_UNTIL]                      VARCHAR (50) NULL,
    [PCS_CARD_SELECT]                          VARCHAR (50) NULL,
    [PCS_CARD_REASON]                          VARCHAR (50) NULL,
    [PCS_CARD_COMPLETE_DATE]                   VARCHAR (50) NULL,
    [TAKE_OVER_STATUS]                         VARCHAR (50) NULL,
    [MEDICALLY_UNDERWRITTEN]                   VARCHAR (50) NULL,
    [COBRA_RECORD_FOR_EMPLOYEE]                VARCHAR (50) NULL,
    [MARIED_OR_SINGLE]                         VARCHAR (50) NULL,
    [DATE_MARRIED]                             VARCHAR (50) NULL,
    [ID_CARD_SELECT]                           VARCHAR (50) NULL,
    [ID_CARD_FORMAT]                           VARCHAR (50) NULL,
    [ID_CARD_RUN_DATE]                         VARCHAR (50) NULL,
    [LABEL_SELECT]                             VARCHAR (50) NULL,
    [LABEL_FORMAT]                             VARCHAR (50) NULL,
    [LABEL_RUN_DATE]                           VARCHAR (50) NULL,
    [CERTIFICATE_SELECT]                       VARCHAR (50) NULL,
    [CERTIFICATE_CARD_FORMAT]                  VARCHAR (50) NULL,
    [CERTIFICATE_RUN_DATE]                     VARCHAR (50) NULL,
    [NUMBER_CHECKS_WRITTEN]                    VARCHAR (50) NULL,
    [DOLLAR_VALUE_OF_CHECKS]                   VARCHAR (50) NULL,
    [RPE_ID]                                   VARCHAR (50) NULL,
    [RPE_MASTER_ID]                            VARCHAR (50) NULL,
    [CONVERTED_EE]                             VARCHAR (50) NULL,
    [PD_THRU_DATE]                             VARCHAR (50) NULL,
    [EXPEDITE_CLAIM]                           VARCHAR (50) NULL,
    [FINANCIAL_CATEGORY]                       VARCHAR (50) NULL,
    [MEDICARE_INDICATOR]                       VARCHAR (50) NULL,
    [HCRA_COUNTY    ]                          VARCHAR (50) NULL,
    [HIPAA_CERTIFICATE_SELECT]                 VARCHAR (50) NULL,
    [HIPAA_CERTIFICATE_CARD_FORMAT]            VARCHAR (50) NULL,
    [HIPAA_CERTIFICATE_RUN_DATE]               VARCHAR (50) NULL,
    [HCRA_EFF_DATE]                            VARCHAR (50) NULL,
    [LAST_UPDATE_DATE]                         VARCHAR (50) NULL,
    [LAST_UPDATE_USER]                         VARCHAR (50) NULL,
    [LOAD_DATE ]                               VARCHAR (50) NULL,
    [LAST_UPDATE_TIME          ]               VARCHAR (50) NULL,
    [EMP_HANDICAP]                             VARCHAR (50) NULL,
    [EMP_FILLER]                               VARCHAR (50) NULL,
    [FSA_CARD]                                 VARCHAR (50) NULL,
    [FSA_DATE_EXTRACTED]                       VARCHAR (50) NULL,
    [LFSA_CARD]                                VARCHAR (50) NULL,
    [LFSA_DATE_EXTRACTED]                      VARCHAR (50) NULL,
    [HRA_CARD]                                 VARCHAR (50) NULL,
    [HRA_DATE_EXTRACTED]                       VARCHAR (50) NULL
);

