CREATE TABLE [dbo].[ELDODEPENDENT] (
    [POLICY_UNDERWRITER_NUMBER]                  VARCHAR (50) NULL,
    [GROUP_NUMBER]                               VARCHAR (50) NULL,
    [EMPLOYEE_SSN]                               VARCHAR (50) NULL,
    [DEPENDENT_SEQUENCE_NUMBER]                  VARCHAR (50) NULL,
    [DATE_LAST_CHANGED]                          VARCHAR (50) NULL,
    [CHANGE_BY]                                  VARCHAR (50) NULL,
    [DEPENDENT_LAST_NAME]                        VARCHAR (50) NULL,
    [DEPENDENT_FIRST_NAME]                       VARCHAR (50) NULL,
    [DEPENDENT_MIDDLE_INITIAL]                   VARCHAR (50) NULL,
    [DEPENDENT_NAME_SUFFIX]                      VARCHAR (50) NULL,
    [DEPENDENT_NAME               ]              VARCHAR (50) NULL,
    [ADDRESS_LINE_1              ]               VARCHAR (50) NULL,
    [ADDRESS_LINE_2                ]             VARCHAR (50) NULL,
    [CITY           ]                            VARCHAR (50) NULL,
    [STATE]                                      VARCHAR (50) NULL,
    [ZIP      ]                                  VARCHAR (50) NULL,
    [HOME_PHONE]                                 VARCHAR (50) NULL,
    [OTHER_PHONE]                                VARCHAR (50) NULL,
    [DATE_OF_BIRTH]                              VARCHAR (50) NULL,
    [SEX]                                        VARCHAR (50) NULL,
    [RELATIONSHIP_TO_EMPLOYEE]                   VARCHAR (50) NULL,
    [DEPENDENT_SSN]                              VARCHAR (50) NULL,
    [NAME_OF_SCHOOL]                             VARCHAR (50) NULL,
    [SEMESTER_HOURS]                             VARCHAR (50) NULL,
    [DATE_DEPENDENT_FIRST_ENROLLED]              VARCHAR (50) NULL,
    [SPECIAL_CODES]                              VARCHAR (50) NULL,
    [USER_DEFINED_ALTERNATE_ID]                  VARCHAR (50) NULL,
    [USER_COMMENT_LINE_1                     ]   VARCHAR (50) NULL,
    [USER_COMMENT_LINE_2]                        VARCHAR (50) NULL,
    [PCS_CARD_SELECT]                            VARCHAR (50) NULL,
    [PCS_CARD_REASON]                            VARCHAR (50) NULL,
    [PCS_CARD_COMPLETE_DATE]                     VARCHAR (50) NULL,
    [TAKEN_OVER]                                 VARCHAR (50) NULL,
    [MEDICALLY_UNDERWRITTEN]                     VARCHAR (50) NULL,
    [PAY_CHECK_TO_EMPLOYEE]                      VARCHAR (50) NULL,
    [MCS_ID]                                     VARCHAR (50) NULL,
    [MCS_NBR]                                    VARCHAR (50) NULL,
    [EXPEDITE_CLAIM]                             VARCHAR (50) NULL,
    [MEDICARE_INDICATOR]                         VARCHAR (50) NULL,
    [HCRA_COUNTY]                                VARCHAR (50) NULL,
    [HCRA_EFFECTIVE_DATE]                        VARCHAR (50) NULL,
    [LAST_UPDATE_DATE]                           VARCHAR (50) NULL,
    [LAST_UPDATE_USER]                           VARCHAR (50) NULL,
    [LOAD_DATE ]                                 VARCHAR (50) NULL,
    [LAST_UPDATE_TIME          ]                 VARCHAR (50) NULL,
    [DEP_HANDICAP]                               VARCHAR (50) NULL,
    [DEP_FILLER                                ] VARCHAR (50) NULL,
    [DEP_CERT_NUMBER]                            VARCHAR (50) NULL,
    [EMP_EOB]                                    VARCHAR (50) NULL
);

