CREATE TABLE [dbo].[ICD9_DIAG1] (
    [IC9_CODE]  VARCHAR (50)  NULL,
    [IC9_DESC]  VARCHAR (MAX) NULL,
    [IC9_DESC2] VARCHAR (50)  NULL,
    [IC9_USE]   VARCHAR (50)  NULL,
    [IC9_VER]   VARCHAR (50)  NULL,
    [IC9_FILL]  VARCHAR (50)  NULL
);

