CREATE TABLE [dbo].[ICD9_DIAG] (
    [IC9_CODE]  VARCHAR (50)   NULL,
    [IC9_DESC ] VARCHAR (1000) NULL,
    [IC9_DESC2] VARCHAR (1000) NULL,
    [IC9_USE]   VARCHAR (50)   NULL,
    [IC9_VER]   VARCHAR (50)   NULL,
    [IC9_FILL]  VARCHAR (50)   NULL
);

