CREATE TABLE [dbo].[MFELDOPENDNEW] (
    [POLICY_UNDERWRITER]             VARCHAR (3)     NULL,
    [GROUP_NUMBER]                   VARCHAR (3)     NULL,
    [CLAIM_NUMBER]                   VARCHAR (11)    NULL,
    [EMPLOYEE_SSN]                   VARCHAR (9)     NULL,
    [DEPENDENT_SEQUENCE_NUMBER]      VARCHAR (2)     NULL,
    [RELATIONSHIP_TO_EMPLOYEE]       VARCHAR (1)     NULL,
    [PATIENT_STATUS]                 VARCHAR (1)     NULL,
    [PATIENT_DATE_OF_BIRTH]          VARCHAR (8)     NULL,
    [EMPLOYEE_DEPARTMENT]            VARCHAR (8)     NULL,
    [DATE_OF_ELIGIBILITY_ENTRY]      VARCHAR (8)     NULL,
    [CLAIM_STATUS]                   VARCHAR (1)     NULL,
    [REPRICING_STATUS]               VARCHAR (1)     NULL,
    [MCS_CLAIM_NUMBER]               VARCHAR (18)    NULL,
    [CASEPAC_CASE_NUMBER]            VARCHAR (8)     NULL,
    [EPISODE_RECORD_NUMBER]          VARCHAR (8)     NULL,
    [REFERRAL_NUMBER]                VARCHAR (8)     NULL,
    [ALTERNATE_ID_1]                 VARCHAR (20)    NULL,
    [ALTERNATE_ID_2]                 VARCHAR (20)    NULL,
    [ALTERNATE_ID_3]                 VARCHAR (20)    NULL,
    [INPUT_BY]                       VARCHAR (6)     NULL,
    [INPUT_DATE]                     VARCHAR (8)     NULL,
    [RECEIVED_DATE]                  VARCHAR (8)     NULL,
    [PAID_DATE]                      VARCHAR (8)     NULL,
    [INCURRED_DATE]                  VARCHAR (8)     NULL,
    [DATE_SENT_TO_PPO_FOR_PRICING]   VARCHAR (8)     NULL,
    [PLAN_YEAR]                      VARCHAR (4)     NULL,
    [DEDUCTIBLE_YEAR]                VARCHAR (4)     NULL,
    [CHANGED_BY]                     VARCHAR (6)     NULL,
    [CHANGED_DATE]                   VARCHAR (8)     NULL,
    [PROCESSED_DATE]                 VARCHAR (8)     NULL,
    [DIAGNOSIS_PAYMENT_GROUP]        VARCHAR (3)     NULL,
    [ICD9_DIAGNOSIS_CODE_1]          VARCHAR (8)     NULL,
    [ICD9_DIAGNOSIS_CODE_2]          VARCHAR (8)     NULL,
    [ICD9_DIAGNOSIS_CODE_3]          VARCHAR (8)     NULL,
    [ICD9_DIAGNOSIS_CODE_4]          VARCHAR (8)     NULL,
    [DIAGNOSIS_CATEGORY]             VARCHAR (30)    NULL,
    [DRG_NUMBER]                     VARCHAR (3)     NULL,
    [NUMBER_OF_PROVIDERS_ON_CLAIM]   VARCHAR (1)     NULL,
    [KEY_TO_PROVIDER_FILE_1]         VARCHAR (8)     NULL,
    [KEY_TO_PROVIDER_FILE_2]         VARCHAR (8)     NULL,
    [KEY_TO_PROVIDER_FILE_3]         VARCHAR (8)     NULL,
    [KEY_TO_PROVIDER_FILE_4]         VARCHAR (8)     NULL,
    [PROVIDER_TAX_ID_1]              VARCHAR (9)     NULL,
    [PROVIDER_TAX_ID_2]              VARCHAR (9)     NULL,
    [PROVIDER_TAX_ID_3]              VARCHAR (9)     NULL,
    [PROVIDER_TAX_ID_4]              VARCHAR (9)     NULL,
    [PROVIDER_ACCOUNT_NUMBER_1]      VARCHAR (20)    NULL,
    [PROVIDER_ACCOUNT_NUMBER_2]      VARCHAR (20)    NULL,
    [PROVIDER_ACCOUNT_NUMBER_3]      VARCHAR (20)    NULL,
    [PROVIDER_ACCOUNT_NUMBER_4]      VARCHAR (20)    NULL,
    [NETWORK_CODE_USED_1]            VARCHAR (5)     NULL,
    [NETWORK_CODE_USED_2]            VARCHAR (5)     NULL,
    [NETWORK_CODE_USED_3]            VARCHAR (5)     NULL,
    [NETWORK_CODE_USED_4]            VARCHAR (5)     NULL,
    [PENALTY_PLAN_USED_1]            VARCHAR (1)     NULL,
    [PENALTY_PLAN_USED_2]            VARCHAR (1)     NULL,
    [PENALTY_PLAN_USED_3]            VARCHAR (1)     NULL,
    [PENALTY_PLAN_USED_4]            VARCHAR (1)     NULL,
    [CHECKING_ACCOUNT_USED_1]        VARCHAR (8)     NULL,
    [CHECKING_ACCOUNT_USED_2]        VARCHAR (8)     NULL,
    [CHECKING_ACCOUNT_USED_3]        VARCHAR (8)     NULL,
    [CHECKING_ACCOUNT_USED_4]        VARCHAR (8)     NULL,
    [CHECKING_ACCOUNT_USED_5]        VARCHAR (8)     NULL,
    [CHECK_NUMBER_USED_1]            VARCHAR (28)    NULL,
    [CHECK_NUMBER_USED_2]            VARCHAR (28)    NULL,
    [CHECK_NUMBER_USED_3]            VARCHAR (28)    NULL,
    [CHECK_NUMBER_USED_4]            VARCHAR (28)    NULL,
    [CHECK_NUMBER_USED_5]            VARCHAR (28)    NULL,
    [PAYMENT_ID_1]                   VARCHAR (20)    NULL,
    [PAYMENT_ID_2]                   VARCHAR (20)    NULL,
    [PAYMENT_ID_3]                   VARCHAR (20)    NULL,
    [PAYMENT_ID_4]                   VARCHAR (20)    NULL,
    [PAYMENT_ID_5]                   VARCHAR (20)    NULL,
    [NET_PAYMENT_AMOUNT_1]           VARCHAR (11)    NULL,
    [NET_PAYMENT_AMOUNT_2]           VARCHAR (11)    NULL,
    [NET_PAYMENT_AMOUNT_3]           VARCHAR (11)    NULL,
    [NET_PAYMENT_AMOUNT_4]           VARCHAR (11)    NULL,
    [NET_PAYMENT_AMOUNT_5]           VARCHAR (11)    NULL,
    [ADJUSTMENT_AMOUNT_1]            VARCHAR (11)    NULL,
    [ADJUSTMENT_AMOUNT_2]            VARCHAR (11)    NULL,
    [ADJUSTMENT_AMOUNT_3]            VARCHAR (11)    NULL,
    [ADJUSTMENT_AMOUNT_4]            VARCHAR (11)    NULL,
    [ADJUSTMENT_AMOUNT_5]            VARCHAR (11)    NULL,
    [NUMBER_OF_SERVICE_LINES_USED]   VARCHAR (1)     NULL,
    [BENEFIT_CODE_1]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_1]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_1]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_1]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_1]          VARCHAR (2)     NULL,
    [FILLER1_1]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_1]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_1]              VARCHAR (2)     NULL,
    [ICD9_POINTER_1]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_1]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_1]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_1]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_1]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_1]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_1]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_1]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_1]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_1]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_1]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_1]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_1]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_1]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_1]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_1]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_1]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_1]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_1]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_1]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_1]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_1]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_1]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_1]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_1]           VARCHAR (11)    NULL,
    [NDC_1]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_1]               VARCHAR (6)     NULL,
    [MODIFIERS1_1]                   VARCHAR (2)     NULL,
    [MODIFIERS2_1]                   VARCHAR (2)     NULL,
    [MODIFIERS3_1]                   VARCHAR (2)     NULL,
    [MODIFIERS4_1]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_1]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_1]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_1]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_1]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_1]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_1]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_1]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_1]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_1]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_1]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_1]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_1]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_1]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_1]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_1]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_1]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_1]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_1]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_1]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_1]     VARCHAR (1)     NULL,
    [TYPE_COB_1]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_1]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_1]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_1]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_1]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_1]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_1]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_1]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_1]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_1]       VARCHAR (8)     NULL,
    [REVENUE_CODE_1]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_1]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_1]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_1]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_1]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_1]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_1]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_1]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_1]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_1]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_1]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_1]                  DECIMAL (7)     NULL,
    [LINE_ITEM_1]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_1]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_2]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_2]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_2]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_2]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_2]          VARCHAR (2)     NULL,
    [FILLER1_2]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_2]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_2]              VARCHAR (2)     NULL,
    [ICD9_POINTER_2]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_2]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_2]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_2]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_2]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_2]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_2]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_2]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_2]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_2]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_2]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_2]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_2]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_2]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_2]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_2]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_2]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_2]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_2]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_2]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_2]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_2]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_2]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_2]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_2]           VARCHAR (11)    NULL,
    [NDC_2]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_2]               VARCHAR (6)     NULL,
    [MODIFIERS1_2]                   VARCHAR (2)     NULL,
    [MODIFIERS2_2]                   VARCHAR (2)     NULL,
    [MODIFIERS3_2]                   VARCHAR (2)     NULL,
    [MODIFIERS4_2]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_2]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_2]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_2]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_2]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_2]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_2]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_2]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_2]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_2]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_2]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_2]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_2]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_2]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_2]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_2]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_2]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_2]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_2]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_2]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_2]     VARCHAR (1)     NULL,
    [TYPE_COB_2]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_2]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_2]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_2]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_2]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_2]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_2]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_2]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_2]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_2]       VARCHAR (8)     NULL,
    [REVENUE_CODE_2]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_2]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_2]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_2]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_2]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_2]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_2]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_2]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_2]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_2]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_2]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_2]                  DECIMAL (7)     NULL,
    [LINE_ITEM_2]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_2]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_3]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_3]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_3]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_3]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_3]          VARCHAR (2)     NULL,
    [FILLER1_3]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_3]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_3]              VARCHAR (2)     NULL,
    [ICD9_POINTER_3]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_3]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_3]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_3]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_3]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_3]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_3]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_3]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_3]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_3]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_3]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_3]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_3]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_3]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_3]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_3]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_3]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_3]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_3]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_3]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_3]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_3]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_3]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_3]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_3]           VARCHAR (11)    NULL,
    [NDC_3]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_3]               VARCHAR (6)     NULL,
    [MODIFIERS1_3]                   VARCHAR (2)     NULL,
    [MODIFIERS2_3]                   VARCHAR (2)     NULL,
    [MODIFIERS3_3]                   VARCHAR (2)     NULL,
    [MODIFIERS4_3]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_3]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_3]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_3]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_3]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_3]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_3]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_3]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_3]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_3]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_3]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_3]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_3]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_3]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_3]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_3]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_3]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_3]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_3]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_3]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_3]     VARCHAR (1)     NULL,
    [TYPE_COB_3]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_3]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_3]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_3]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_3]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_3]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_3]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_3]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_3]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_3]       VARCHAR (8)     NULL,
    [REVENUE_CODE_3]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_3]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_3]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_3]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_3]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_3]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_3]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_3]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_3]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_3]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_3]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_3]                  DECIMAL (7)     NULL,
    [LINE_ITEM_3]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_3]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_4]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_4]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_4]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_4]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_4]          VARCHAR (2)     NULL,
    [FILLER1_4]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_4]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_4]              VARCHAR (2)     NULL,
    [ICD9_POINTER_4]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_4]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_4]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_4]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_4]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_4]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_4]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_4]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_4]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_4]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_4]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_4]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_4]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_4]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_4]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_4]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_4]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_4]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_4]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_4]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_4]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_4]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_4]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_4]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_4]           VARCHAR (11)    NULL,
    [NDC_4]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_4]               VARCHAR (6)     NULL,
    [MODIFIERS1_4]                   VARCHAR (2)     NULL,
    [MODIFIERS2_4]                   VARCHAR (2)     NULL,
    [MODIFIERS3_4]                   VARCHAR (2)     NULL,
    [MODIFIERS4_4]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_4]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_4]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_4]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_4]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_4]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_4]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_4]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_4]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_4]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_4]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_4]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_4]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_4]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_4]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_4]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_4]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_4]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_4]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_4]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_4]     VARCHAR (1)     NULL,
    [TYPE_COB_4]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_4]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_4]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_4]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_4]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_4]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_4]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_4]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_4]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_4]       VARCHAR (8)     NULL,
    [REVENUE_CODE_4]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_4]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_4]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_4]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_4]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_4]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_4]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_4]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_4]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_4]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_4]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_4]                  DECIMAL (7)     NULL,
    [LINE_ITEM_4]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_4]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_5]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_5]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_5]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_5]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_5]          VARCHAR (2)     NULL,
    [FILLER1_5]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_5]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_5]              VARCHAR (2)     NULL,
    [ICD9_POINTER_5]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_5]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_5]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_5]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_5]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_5]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_5]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_5]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_5]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_5]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_5]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_5]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_5]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_5]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_5]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_5]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_5]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_5]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_5]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_5]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_5]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_5]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_5]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_5]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_5]           VARCHAR (11)    NULL,
    [NDC_5]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_5]               VARCHAR (6)     NULL,
    [MODIFIERS1_5]                   VARCHAR (2)     NULL,
    [MODIFIERS2_5]                   VARCHAR (2)     NULL,
    [MODIFIERS3_5]                   VARCHAR (2)     NULL,
    [MODIFIERS4_5]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_5]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_5]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_5]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_5]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_5]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_5]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_5]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_5]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_5]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_5]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_5]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_5]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_5]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_5]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_5]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_5]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_5]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_5]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_5]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_5]     VARCHAR (1)     NULL,
    [TYPE_COB_5]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_5]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_5]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_5]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_5]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_5]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_5]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_5]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_5]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_5]       VARCHAR (8)     NULL,
    [REVENUE_CODE_5]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_5]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_5]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_5]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_5]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_5]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_5]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_5]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_5]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_5]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_5]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_5]                  DECIMAL (7)     NULL,
    [LINE_ITEM_5]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_5]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_6]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_6]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_6]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_6]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_6]          VARCHAR (2)     NULL,
    [FILLER1_6]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_6]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_6]              VARCHAR (2)     NULL,
    [ICD9_POINTER_6]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_6]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_6]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_6]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_6]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_6]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_6]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_6]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_6]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_6]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_6]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_6]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_6]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_6]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_6]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_6]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_6]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_6]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_6]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_6]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_6]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_6]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_6]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_6]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_6]           VARCHAR (11)    NULL,
    [NDC_6]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_6]               VARCHAR (6)     NULL,
    [MODIFIERS1_6]                   VARCHAR (2)     NULL,
    [MODIFIERS2_6]                   VARCHAR (2)     NULL,
    [MODIFIERS3_6]                   VARCHAR (2)     NULL,
    [MODIFIERS4_6]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_6]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_6]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_6]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_6]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_6]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_6]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_6]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_6]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_6]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_6]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_6]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_6]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_6]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_6]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_6]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_6]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_6]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_6]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_6]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_6]     VARCHAR (1)     NULL,
    [TYPE_COB_6]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_6]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_6]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_6]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_6]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_6]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_6]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_6]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_6]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_6]       VARCHAR (8)     NULL,
    [REVENUE_CODE_6]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_6]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_6]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_6]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_6]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_6]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_6]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_6]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_6]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_6]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_6]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_6]                  DECIMAL (7)     NULL,
    [LINE_ITEM_6]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_6]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_7]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_7]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_7]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_7]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_7]          VARCHAR (2)     NULL,
    [FILLER1_7]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_7]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_7]              VARCHAR (2)     NULL,
    [ICD9_POINTER_7]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_7]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_7]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_7]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_7]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_7]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_7]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_7]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_7]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_7]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_7]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_7]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_7]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_7]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_7]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_7]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_7]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_7]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_7]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_7]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_7]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_7]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_7]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_7]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_7]           VARCHAR (11)    NULL,
    [NDC_7]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_7]               VARCHAR (6)     NULL,
    [MODIFIERS1_7]                   VARCHAR (2)     NULL,
    [MODIFIERS2_7]                   VARCHAR (2)     NULL,
    [MODIFIERS3_7]                   VARCHAR (2)     NULL,
    [MODIFIERS4_7]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_7]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_7]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_7]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_7]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_7]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_7]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_7]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_7]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_7]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_7]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_7]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_7]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_7]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_7]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_7]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_7]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_7]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_7]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_7]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_7]     VARCHAR (1)     NULL,
    [TYPE_COB_7]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_7]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_7]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_7]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_7]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_7]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_7]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_7]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_7]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_7]       VARCHAR (8)     NULL,
    [REVENUE_CODE_7]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_7]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_7]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_7]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_7]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_7]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_7]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_7]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_7]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_7]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_7]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_7]                  DECIMAL (7)     NULL,
    [LINE_ITEM_7]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_7]          VARCHAR (274)   NULL,
    [BENEFIT_CODE_8]                 VARCHAR (3)     NULL,
    [BENEFIT_CATEGORY_8]             VARCHAR (30)    NULL,
    [FROM_DATE_OF_SERVICE_8]         VARCHAR (8)     NULL,
    [THRU_DATE_OF_SERVICE_8]         VARCHAR (8)     NULL,
    [EMERGENCY_INDICATOR_8]          VARCHAR (2)     NULL,
    [FILLER1_8]                      VARCHAR (1)     NULL,
    [PLACE_OF_SERVICE_8]             VARCHAR (2)     NULL,
    [TYPE_OF_SERVICE_8]              VARCHAR (2)     NULL,
    [ICD9_POINTER_8]                 VARCHAR (12)    NULL,
    [CHARGE_AMOUNT_8]                DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED_8]             DECIMAL (12, 2) NULL,
    [INELIGIBLE_AMOUNT_8]            DECIMAL (12, 2) NULL,
    [COPAYMENT_AMOUNT_8]             DECIMAL (12, 2) NULL,
    [DISCOUNT_AMOUNT_8]              DECIMAL (12, 2) NULL,
    [DEDUCTIBLE_AMOUNT_8]            DECIMAL (12, 2) NULL,
    [OVER_USUAL_CUSTOMARY_8]         DECIMAL (12, 2) NULL,
    [DENIED_BY_MCS_8]                DECIMAL (12, 2) NULL,
    [PENALTY_AMOUNT_8]               DECIMAL (12, 2) NULL,
    [OTHER_USER_DEFINED_8]           DECIMAL (12, 2) NULL,
    [CLAIM_COUNT_8]                  DECIMAL (4)     NULL,
    [NUMBER_OF_SERVICE_DAYS_8]       DECIMAL (4)     NULL,
    [OUT_OF_POCKET_AMOUNT_8]         DECIMAL (12, 2) NULL,
    [PATIENT_RESPONSIBILITY_8]       DECIMAL (12, 2) NULL,
    [ANESTHESIA_MINUTES_8]           VARCHAR (3)     NULL,
    [PROVIDER_OF_SERVICE_PTR_8]      DECIMAL (1)     NULL,
    [COINSURANCE_PERCENTAGE_8]       DECIMAL (3)     NULL,
    [PAYMENT_AMOUNT_8]               DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDER_8]             DECIMAL (12, 2) NULL,
    [PAID_TO_PATIENT_8]              DECIMAL (12, 2) NULL,
    [WITHHOLD_AMOUNT_8]              DECIMAL (12, 2) NULL,
    [CAPITATED_AMOUNT_8]             DECIMAL (12, 2) NULL,
    [CAPITATION_ACCOUNT_8]           VARCHAR (8)     NULL,
    [NATIONAL_DRUG_CODE_8]           VARCHAR (11)    NULL,
    [NDC_8]                          VARCHAR (1)     NULL,
    [PROCEDURE_CODE_8]               VARCHAR (6)     NULL,
    [MODIFIERS1_8]                   VARCHAR (2)     NULL,
    [MODIFIERS2_8]                   VARCHAR (2)     NULL,
    [MODIFIERS3_8]                   VARCHAR (2)     NULL,
    [MODIFIERS4_8]                   VARCHAR (2)     NULL,
    [BILLED_PROCEDURE_8]             VARCHAR (6)     NULL,
    [INELIGIBLE_REASON_CODE_8]       VARCHAR (2)     NULL,
    [OVER_UC_REASON_CODE_8]          VARCHAR (2)     NULL,
    [DISCOUNT_REASON_CODE_8]         VARCHAR (2)     NULL,
    [COPAYMENT_REASON_CODE_8]        VARCHAR (2)     NULL,
    [DENIED_BY_MCS_REASON_CODE_8]    VARCHAR (2)     NULL,
    [PENALTY_REASON_CODE_8]          VARCHAR (2)     NULL,
    [NOT_COVERED_OTH_REASON_CODE_8]  VARCHAR (2)     NULL,
    [DEDUCTIBLE_ACCUM_BUCKET_8]      DECIMAL (2)     NULL,
    [OUTOFPOCKET_ACCUM_BUCKET_8]     DECIMAL (2)     NULL,
    [OUTOFPOCKET_TYPE_8]             VARCHAR (1)     NULL,
    [BENEFIT_EXCEPTION_BUCKET_8]     DECIMAL (3)     NULL,
    [COPAYMENT_ACCUM_BUCKET_8]       DECIMAL (3)     NULL,
    [HISTORY_BUCKET_POINTER_8]       DECIMAL (2)     NULL,
    [HISTORY_ENTRY_POINTER_8]        DECIMAL (2)     NULL,
    [MCS_CLAIM_LINE_8]               DECIMAL (3)     NULL,
    [ROLLOVER_OCCURED_8]             VARCHAR (1)     NULL,
    [COPAYMENTS_TAKEN_8]             DECIMAL (2)     NULL,
    [AMOUNT_DENIED_BY_MCS_8]         DECIMAL (12, 2) NULL,
    [WHERE_AMOUNT_SHOUD_APPLY_8]     VARCHAR (1)     NULL,
    [TYPE_COB_8]                     VARCHAR (1)     NULL,
    [COB_AMOUNT_EMPLOYEE_8]          DECIMAL (12, 2) NULL,
    [COB_AMOUNT_PROVIDER_8]          DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_NOT_PAID_8]       DECIMAL (12, 2) NULL,
    [CR_RSRV_ALLOW_AMOUNT_8]         DECIMAL (12, 2) NULL,
    [CR_RSRV_SAVINGS_AMOUNT_8]       DECIMAL (12, 2) NULL,
    [CR_RSRV_COB_CREDITS_8]          DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID_8]         DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS_8]         VARCHAR (1)     NULL,
    [BENEFIT_ACCUM_EVENT_ID_8]       VARCHAR (8)     NULL,
    [REVENUE_CODE_8]                 VARCHAR (4)     NULL,
    [SURCHARGE_ADDED_TO_CLAIM_8]     DECIMAL (12, 2) NULL,
    [TAX_TO_BE_PAID_ON_CLAIM_8]      DECIMAL (12, 2) NULL,
    [STATE_SURCHARGE_PAID_TO_8]      CHAR (2)        NULL,
    [ORIG_CODE_FOR_SUPP_8]           CHAR (3)        NULL,
    [DISALLOWED_VISITS_8]            DECIMAL (4)     NULL,
    [ORIG_INELG_AMT_FROM_PRICING_8]  DECIMAL (12, 2) NULL,
    [S1EXPAMT_8]                     DECIMAL (12, 2) NULL,
    [S1EXPUNIT_8]                    VARCHAR (1)     NULL,
    [S1ORIGBEN_8]                    VARCHAR (3)     NULL,
    [ICD9_NEW_POINTER_8]             VARCHAR (12)    NULL,
    [CLAIM_UNITS_8]                  DECIMAL (7)     NULL,
    [LINE_ITEM_8]                    VARCHAR (30)    NULL,
    [SERVICE_LINE_FILLER_8]          VARCHAR (274)   NULL,
    [CHARGE_AMOUNT]                  DECIMAL (12, 2) NULL,
    [TOTAL_DISALLOWED]               DECIMAL (12, 2) NULL,
    [TOTAL_INELIGIBLE_AMOUNT]        DECIMAL (12, 2) NULL,
    [TOTAL_COPAYMENT_AMOUNT]         DECIMAL (12, 2) NULL,
    [TOTAL_OVER_USUAL_CUSTOMARY]     DECIMAL (12, 2) NULL,
    [TOTAL_PROVIDER_DISCOUNT_AMOUNT] DECIMAL (12, 2) NULL,
    [TOTAL_ORIGINAL_DISCOUNT_AMOUNT] DECIMAL (12, 2) NULL,
    [TOTAL_DEDUCTIBLE]               DECIMAL (12, 2) NULL,
    [TOTAL_PENALTY_AMOUNT]           DECIMAL (12, 2) NULL,
    [TOTAL_NOT_COVERED_AMOUNT]       DECIMAL (12, 2) NULL,
    [TOTAL_COINSURANCE]              DECIMAL (12, 2) NULL,
    [TOTAL_OUTOF_POCKET]             DECIMAL (12, 2) NULL,
    [TOTAL_PATIENT_RESP_AMOUNT]      DECIMAL (12, 2) NULL,
    [TOTAL_CLAIM_PAID_AMOUNT]        DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDERS1]             DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDERS2]             DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDERS3]             DECIMAL (12, 2) NULL,
    [PAID_TO_PROVIDERS4]             DECIMAL (12, 2) NULL,
    [PAID_TO_EMPLOYEE]               DECIMAL (12, 2) NULL,
    [COB_LEVEL_APPLIED_FLAG]         VARCHAR (1)     NULL,
    [COB_SAVINGS]                    VARCHAR (11)    NULL,
    [COB_ALLOWED_NOT_PAID]           VARCHAR (11)    NULL,
    [COB_ADJUSTMENT_1]               VARCHAR (11)    NULL,
    [COB_ADJUSTMENT_2]               VARCHAR (11)    NULL,
    [COB_ADJUSTMENT_3]               VARCHAR (11)    NULL,
    [COB_ADJUSTMENT_4]               VARCHAR (11)    NULL,
    [COB_ADJUSTMENT_5]               VARCHAR (11)    NULL,
    [TYPE_COB]                       VARCHAR (1)     NULL,
    [CR_RESERVE_ALLOWED_NOT_PAID]    DECIMAL (12, 2) NULL,
    [CR_RESERVE_ALLOWED_AMOUNT]      DECIMAL (12, 2) NULL,
    [CR_RESERVE_SAVINGS_AMOUNT]      DECIMAL (12, 2) NULL,
    [CR_RESERVE_COB_CREDITS]         DECIMAL (12, 2) NULL,
    [OTHER_INSURANCE_PAID]           DECIMAL (12, 2) NULL,
    [UPDATE_COB_TO_ACCUMS]           VARCHAR (1)     NULL,
    [CLAIMS_PRODUCT_CODE]            VARCHAR (2)     NULL,
    [PLAN_CODE_USED]                 VARCHAR (10)    NULL,
    [PLAN_EFFECTIVE_DATE]            VARCHAR (8)     NULL,
    [CLAIM_SOURCE]                   VARCHAR (1)     NULL,
    [CLAIM_PLNFILL]                  VARCHAR (1)     NULL,
    [EOB_MESSAGE_KEY]                VARCHAR (3)     NULL,
    [CLAIM_REMARKS_1]                VARCHAR (75)    NULL,
    [CLAIM_REMARKS_2]                VARCHAR (75)    NULL,
    [PENDED_REASON_CODE]             VARCHAR (3)     NULL,
    [HOLD_CLAIM_FROM_PAYMENT]        VARCHAR (1)     NULL,
    [HOLD_CLAIM_FOR_STOP_LOSS]       VARCHAR (1)     NULL,
    [CLAIM_RESERVED_BY_ENDDAY]       VARCHAR (1)     NULL,
    [TOOTH_CHART_INFORMATION]        VARCHAR (1)     NULL,
    [NETWORK_IND_DEDUCTIBLE_MET]     DECIMAL (12, 2) NULL,
    [NETWORK_FAMILY_DEDUCTIBLE_MET]  DECIMAL (12, 2) NULL,
    [NETWORK_IND_DEDUCT_MAXIMUM]     DECIMAL (12, 2) NULL,
    [NETWORK_FAMILY_DEDUCT_MAXIMUM]  DECIMAL (12, 2) NULL,
    [STANDARD_IND_DEDUCTIBLE_MET]    DECIMAL (12, 2) NULL,
    [STANDARD_FAMILY_DEDUCTIBLE_MET] DECIMAL (12, 2) NULL,
    [STANDARD_IND_DEDUCT_MAXIMUM]    DECIMAL (12, 2) NULL,
    [STANDARD_FAMILY_DEDUCT_MAXIMUM] DECIMAL (12, 2) NULL,
    [NETWORK_IND_OUT_POCKET_MET]     DECIMAL (12, 2) NULL,
    [NETWORK_FAMILY_OUT_POCKET_MET]  DECIMAL (12, 2) NULL,
    [NETWORK_IND_OUTPKT_MAXIMUM]     DECIMAL (12, 2) NULL,
    [NETWORK_FAMILY_OUTPKT_MAXIMUM]  DECIMAL (12, 2) NULL,
    [STANDARD_IND_OUT_POCKET_MET]    DECIMAL (12, 2) NULL,
    [STANDARD_FAMILY_OUT_POCKET_MET] DECIMAL (12, 2) NULL,
    [STANDARD_IND_OUTPKT_MAXIMUM]    DECIMAL (12, 2) NULL,
    [STANDARD_FAMILY_OUTPKT_MAXIMUM] DECIMAL (12, 2) NULL,
    [CLAIM_ADJ_REASON_CODE]          VARCHAR (4)     NULL,
    [CLAIM_ADJUST]                   VARCHAR (1)     NULL,
    [MANUAL_WORKFLOW_QUEUE]          VARCHAR (10)    NULL,
    [CLAIM_CONVERT]                  VARCHAR (1)     NULL,
    [CLAIM_CNVACC]                   VARCHAR (1)     NULL,
    [CLAIM_CNVDATE]                  VARCHAR (8)     NULL,
    [CLAIM_CNV1099]                  VARCHAR (1)     NULL,
    [CLAIM_CHGDATE_FORM_TYPE]        VARCHAR (1)     NULL,
    [CLAIM_NUM_CONNECTION_1]         VARCHAR (11)    NULL,
    [CLAIM_NUM_CONNECTION_2]         VARCHAR (11)    NULL,
    [CLAIM_NUM_CONNECTION_3]         VARCHAR (11)    NULL,
    [CLAIM_NUM_CONNECTION_4]         VARCHAR (11)    NULL,
    [CLAIM_UB92PROC_1]               VARCHAR (8)     NULL,
    [CLAIM_UB92PROC_2]               VARCHAR (8)     NULL,
    [CLAIM_UB92PROC_3]               VARCHAR (8)     NULL,
    [CLAIM_UB92PROC_4]               VARCHAR (8)     NULL,
    [CLAIM_UB92PROC_5]               VARCHAR (8)     NULL,
    [CLAIM_UB92PROC_6]               VARCHAR (8)     NULL,
    [CLAIM_VERSION]                  VARCHAR (2)     NULL,
    [CLAIM_NETWORK_USED_KEY_1]       VARCHAR (21)    NULL,
    [CLAIM_NETWORK_USED_KEY_2]       VARCHAR (21)    NULL,
    [CLAIM_NETWORK_USED_KEY_3]       VARCHAR (21)    NULL,
    [CLAIM_NETWORK_USED_KEY_4]       VARCHAR (21)    NULL,
    [CLAIM_PCERT_OBTAINED_1]         VARCHAR (1)     NULL,
    [CLAIM_PCERT_OBTAINED_2]         VARCHAR (1)     NULL,
    [CLAIM_PCERT_OBTAINED_3]         VARCHAR (1)     NULL,
    [CLAIM_PCERT_OBTAINED_4]         VARCHAR (1)     NULL,
    [CLAIM_PCERT_OBTAINED_5]         VARCHAR (1)     NULL,
    [CLAIM_TIFF_IND]                 VARCHAR (30)    NULL,
    [CLAIM_MAILCODE]                 VARCHAR (2)     NULL,
    [CLAIM_TAXTYPE_USED]             VARCHAR (2)     NULL,
    [CLAIM_PAYRFND]                  VARCHAR (1)     NULL,
    [CLAIM_ALTPAYID]                 VARCHAR (8)     NULL,
    [CLAIM_ALTPAYFG]                 VARCHAR (1)     NULL,
    [CLAIM_HCISENT]                  VARCHAR (1)     NULL,
    [CLAIM_OVERFLAG]                 VARCHAR (1)     NULL,
    [CLAIM_PX_CAT_KEY]               VARCHAR (38)    NULL,
    [CLAIM_PER_OCC_ACC_EVENT]        VARCHAR (8)     NULL,
    [CLAIM_REFERAL]                  VARCHAR (1)     NULL,
    [CLAIM_REFSCHD]                  VARCHAR (26)    NULL,
    [CLAIM_DVISITS]                  DECIMAL (4)     NULL,
    [CLAIM_ACEVYR]                   VARCHAR (4)     NULL,
    [ALLOWED_VISITS]                 VARCHAR (4)     NULL,
    [AMPS_ON_NEG]                    VARCHAR (1)     NULL,
    [PAID_BY_STOP_LOSS_CARRIER]      VARCHAR (1)     NULL,
    [CLAIM_NOT_ALLOWED_CHECK_RUN]    VARCHAR (1)     NULL,
    [ACCOUNT_TYPE]                   VARCHAR (1)     NULL,
    [LFSA_PROD]                      VARCHAR (1)     NULL,
    [EFT_CHECK1]                     VARCHAR (1)     NULL,
    [EFT_CHECK2]                     VARCHAR (1)     NULL,
    [EFT_CHECK3]                     VARCHAR (1)     NULL,
    [EFT_CHECK4]                     VARCHAR (1)     NULL,
    [EFT_CHECK5]                     VARCHAR (1)     NULL,
    [PMCS_INDICATOR]                 VARCHAR (1)     NULL,
    [PMCS_CLAIM_ID]                  VARCHAR (8)     NULL,
    [PMCS_DUE_DATE]                  VARCHAR (8)     NULL,
    [ORIG_PAYMENT_FOR_PMCS_ADJ]      VARCHAR (12)    NULL,
    [ICD_CODE_1]                     VARCHAR (8)     NULL,
    [ICD_CODE_2]                     VARCHAR (8)     NULL,
    [ICD_CODE_3]                     VARCHAR (8)     NULL,
    [ICD_CODE_4]                     VARCHAR (8)     NULL,
    [ICD_CODE_5]                     VARCHAR (8)     NULL,
    [ICD_CODE_6]                     VARCHAR (8)     NULL,
    [ICD_CODE_7]                     VARCHAR (8)     NULL,
    [ICD_CODE_8]                     VARCHAR (8)     NULL,
    [ICD_VERSION]                    VARCHAR (2)     NULL,
    [CLAIM_VENDOR]                   VARCHAR (1)     NULL,
    [VENDOR_CHECK]                   VARCHAR (1)     NULL,
    [EPAY]                           VARCHAR (1)     NULL,
    [OOP_ACCUMULATOR]                VARCHAR (12)    NULL,
    [DED_ACCUMULATOR]                VARCHAR (12)    NULL,
    [EPAY_835]                       VARCHAR (1)     NULL
);

