CREATE TABLE [dbo].[TEMP_ELDO_DISBLTY_CONTROLS] (
    [BATCH_FROM_DATE]     VARCHAR (8)  NOT NULL,
    [BATCH_TO_DATE]       VARCHAR (8)  NOT NULL,
    [BATCH_TOTAL_CLAIMS]  VARCHAR (9)  NOT NULL,
    [BATCH_TOTAL_LINES]   VARCHAR (9)  NOT NULL,
    [BATCH_TOTAL_CHARGES] VARCHAR (14) NOT NULL,
    [BATCH_TOTAL_PAID]    VARCHAR (14) NOT NULL,
    [BATCH_TOTAL_VOIDS]   VARCHAR (15) NULL,
    [BATCH_TOTAL_NET]     VARCHAR (14) NOT NULL
);

