-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[INSERT_MFELDOPAIDNEW] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

BEGIN TRANSACTION; 

BEGIN TRY  

INSERT INTO claims.DBO.eldoclmsheader(
POLICY_UNDERWRITER,
GROUP_NUMBER,
CLAIM_NUMBER,
EMPLOYEE_SSN,
DEPENDENT_SEQUENCE_NUMBER,
RELATIONSHIP_TO_EMPLOYEE,
PATIENT_STATUS,
PATIENT_DATE_OF_BIRTH,
EMPLOYEE_DEPARTMENT,
DATE_OF_ELIGIBILITY_ENTRY,
CLAIM_STATUS,
REPRICING_STATUS,
MCS_CLAIM_NUMBER,
CASEPAC_CASE_NUMBER,
PRECERT_NUMBER,
REFERRAL_NUMBER,
ALTERNATE_ID_1,
ALTERNATE_ID_2,
ALTERNATE_ID_3,
INPUT_BY,
PAID_DATE,
INPUT_DATE,
RECEIVED_DATE,
PPO_PRICING_SENT_DATE,
INCURRED_DATE,
PLAN_YEAR,
DEDUCTIBLE_YEAR,
CHANGED_BY,
CHANGED_DATE,
PROCESSED_DATE,
DIAGNOSIS_PAYMENT_GROUP,
ICD9_DIAGNOSIS_CODE_1,
ICD9_DIAGNOSIS_CODE_2,
ICD9_DIAGNOSIS_CODE_3,
ICD9_DIAGNOSIS_CODE_4,
DIAGNOSIS_CATEGORY,
DRG_NUMBER,
NUMBER_OF_PROVIDERS_ON_CLAIM,
KEY_TO_PROVIDER_FILE_1,
KEY_TO_PROVIDER_FILE_2,
KEY_TO_PROVIDER_FILE_3,
KEY_TO_PROVIDER_FILE_4,
PROVIDER_TAX_ID_1,
PROVIDER_TAX_ID_2,
PROVIDER_TAX_ID_3,
PROVIDER_TAX_ID_4,
PROVIDER_ACCOUNT_NUMBER_1,
PROVIDER_ACCOUNT_NUMBER_2,
PROVIDER_ACCOUNT_NUMBER_3,
PROVIDER_ACCOUNT_NUMBER_4,
NETWORK_CODE_USED_1,
NETWORK_CODE_USED_2,
NETWORK_CODE_USED_3,
NETWORK_CODE_USED_4,
PENALTY_PLAN_USED_1,
PENALTY_PLAN_USED_2,
PENALTY_PLAN_USED_3,
PENALTY_PLAN_USED_4,
CHECKING_ACCOUNT_USED_1,
CHECKING_ACCOUNT_USED_2,
CHECKING_ACCOUNT_USED_3,
CHECKING_ACCOUNT_USED_4,
CHECKING_ACCOUNT_USED_5,
CHECK_NUMBER_USED_1,
CHECK_NUMBER_USED_2,
CHECK_NUMBER_USED_3,
CHECK_NUMBER_USED_4,
CHECK_NUMBER_USED_5,
NET_PAYMENT_AMOUNT_1,
NET_PAYMENT_AMOUNT_2,
NET_PAYMENT_AMOUNT_3,
NET_PAYMENT_AMOUNT_4,
NET_PAYMENT_AMOUNT_5,
ADJUSTMENT_AMOUNT_1,
ADJUSTMENT_AMOUNT_2,
ADJUSTMENT_AMOUNT_3,
ADJUSTMENT_AMOUNT_4,
ADJUSTMENT_AMOUNT_5,
NUMBER_OF_SERVICE_LINES_USED,
TOTAL_CHARGE_AMOUNT,
TOTAL_DISALLOWED,
TOTAL_INELIGIBLE,
TOTAL_COPAYMENT,
TOTAL_OVER_UC,
TOTAL_PROVIDER_DISCOUNTS,
TOTAL_DENIED_BY_MCS,
TOTAL_DEDUCTIBLE,
TOTAL_PENALTY_AMOUNT,
TOTAL_NOT_COVERED_OTHER,
TOTAL_COINSURANCE,
TOTAL_OUTOFPOCKET,
TOTAL_PATIENT_RESPONSIBILITY,
TOTAL_CLAIM_PAID,
TOTAL_PAID_TO_PROVIDERS_1,
TOTAL_PAID_TO_PROVIDERS_2,
TOTAL_PAID_TO_PROVIDERS_3,
TOTAL_PAID_TO_PROVIDERS_4,
TOTAL_PAID_TO_EMPLOYEE,
COB_LEVEL_APPLIED_FLAG,
COB_SAVINGS,
COB_ALLOWED_NOT_PAID,
COB_ADJUSTMENT_1,
COB_ADJUSTMENT_2,
COB_ADJUSTMENT_3,
COB_ADJUSTMENT_4,
COB_ADJUSTMENT_5,
TYPE_COB,
CR_RESERVE_ALLOWED_NOT_PAID,
CR_RESERVE_ALLOWED_AMOUNT,
CR_RESERVE_SAVINGS_AMOUNT,
CR_RESERVE_COB_CREDITS,
OTHER_INSURANCE_PAID,
UPDATE_COB_TO_ACCUMS,
PRODUCT_CODE,
--POLICY_FILE_KEY_USED_1,
--POLICY_FILE_KEY_USED_2,
--POLICY_FILE_KEY_USED_3,
--POLICY_FILE_KEY_USED_4,
--POLICY_FILE_KEY_USED_5,
--CLASS_CODE_USED,
PLAN_CODE_USED,
REPRICED_BY,
HEALTHPAC_PRICING_DATA,
EOB_MESSAGE_KEY,
CLAIM_REMARKS_1,
CLAIM_REMARKS_2,
PENDED_REASON_CODE,
HOLD_CLAIM_FROM_PAYMENT,
HOLD_CLAIM_FOR_STOP_LOSS,
CLAIM_RESERVED_BY_ENDDAY,
TOOTH_CHART_INFORMATION,
INDIVIDUAL_DEDUCTIBLE_MET_1,
FAMILY_DEDUCTIBLE_MET_1,
INDIVIDUAL_DEDUCTIBLE_MAX_1,
FAMILY_DEDUCTIBLE_MAX_1,
INDIVIDUAL_OUTOFPOCKET_MET_1,
FAMILY_OUTOFPOCKET_MET_1,
INDIVIDUAL_OUTOFPOCKET_MAX_1,
FAMILY_OUTOFPOCKET_MAX_1,
CLAIM_CONVERTED,
CLAIM_USE_REBUILD,
CLAIM_CONVERTED_DATE,
CONV_CLAIM_1099,
FORM_TYPE,
CLAIM_NUMBERING_CONNECTION_1,
CLAIM_NUMBERING_CONNECTION_2,
CLAIM_NUMBERING_CONNECTION_3,
CLAIM_NUMBERING_CONNECTION_4,
UB92_CLAIM_LEVEL_DISCOUNT_1,
UB92_CLAIM_LEVEL_DISCOUNT_2,
UB92_CLAIM_LEVEL_DISCOUNT_3,
UB92_CLAIM_LEVEL_DISCOUNT_4,
KEY_TO_PPO_NETWORK_USED_1,
KEY_TO_PPO_NETWORK_USED_2,
KEY_TO_PPO_NETWORK_USED_3,
KEY_TO_PPO_NETWORK_USED_4,
PRECERTIFICATION_OBTAINED_1,
PRECERTIFICATION_OBTAINED_2,
PRECERTIFICATION_OBTAINED_3,
PRECERTIFICATION_OBTAINED_4,
PRECERTIFICATION_OBTAINED_5,
TIFF_IMAGE_IDENTIFIER,
MAIL_ROUTING_CODE,
TAX_TYPE_USED,
LOAD_DATE,
ATTACH_IND,
PLAN_EFFECTIVE_DATE,
CLAIM_PLNFILL,
Standard_Ind_Deductible_Met,
Standard_Family_Deductible_Met,
Standard_Ind_Deduct_Maximum,
Standard_Family_Deduct_Maximum,
Standard_Ind_Out_pocket_Met,
Standard_Family_Out_pocket_Met,
Standard_Ind_Outpkt_Maximum,
Standard_Family_Outpkt_Maximum,
CLAIM_ADJ_REASON_CODE,
CLAIM_ADJUST,
MANUAL_WORKFLOW_QUEUE,
--CLAIM_INC_DATE,
CLAIM_UB92PROC_1,
CLAIM_UB92PROC_2,
CLAIM_UB92PROC_3,
CLAIM_UB92PROC_4,
CLAIM_UB92PROC_5,
CLAIM_UB92PROC_6,
CLAIM_VERSION,
CLAIM_ALT_Provider_ID,
CLAIM_ALTPAYFG,
CLAIM_HCISENT,
CLAIM_PX_CAT_KEY,
CLAIM_PER_OCC_ACC_EVENT,
CLAIM_REFERAL,
CLAIM_REFSCHD_USED,
CLAIM_TOTAL_VISITS,
CLAIM_ACEVYR,
CLAIM_REFSCHD,
CLAIM_PER_OCC_ACC_EVENT_YR,
--CLAIM_FILLER,
--Dirigo_Savings_Offset_Premiums,
--AMPS_Out_of_Network_Negotiated,
--Paid_by_Stop_Loss_Carrier,
--Claim_not_allowed_check_run,
--Account_Type    
ALLOWED_VISITS,
--AMPS_OO_NETWORK_NEGOTIATED_2,
--PAID_BY_STOPLOSS_2,
--HLDGRP_PAID2,
--ACCOUNT_TYPE_2,
LFSA_PROD,
EFT_CHECK1,
EFT_CHECK2,
EFT_CHECK3,
EFT_CHECK4,
EFT_CHECK5,
PMCS_INDICATOR,
PMCS_CLAIM_ID,
PMCS_DUE_DATE,
ORIG_PAYMENT_FOR_PMCS_ADJ,
ICD_CODE_1,
ICD_CODE_2,
ICD_CODE_3,
ICD_CODE_4,
ICD_CODE_5,
ICD_CODE_6,
ICD_CODE_7,
ICD_CODE_8,
ICD_VERSION,
CLAIM_VENDOR,
VENDOR_CHECK,
EPAY,
OOP_ACCUMULATOR,
DED_ACCUMULATOR,
EPAY_835
)   
select distinct
t.Policy_Underwriter ,
t.Group_Number ,
t.Claim_Number ,
t.Employee_SSN ,
--decimal(ltrim(t.Dependent_Sequence_Number),2,0),
dbo.ufn_Convert_to_Decimal(t.Dependent_Sequence_Number),
t.Relationship_to_Employee ,
t.Patient_Status ,
--CASE CLAIMS.ISDATECHECK(t.Patient_Date_Of_Birth) WHEN 0 THEN NULL ELSE case ltrim(t.Patient_Date_Of_Birth) when '' then null when ' ' then null else date(substr(t.Patient_Date_Of_Birth,1,4)||'-' ||substr(t.Patient_Date_Of_Birth,5,2)||'-' ||substr(t.Patient_Date_Of_Birth,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Patient_Date_Of_Birth),
t.Employee_Department ,
--CASE CLAIMS.ISDATECHECK(t.Date_Of_Eligibility_Entry) WHEN 0 THEN NULL ELSE case ltrim(t.Date_Of_Eligibility_Entry) when '' then null when ' ' then null else date(substr(t.Date_Of_Eligibility_Entry,1,4)||'-' ||substr(t.Date_Of_Eligibility_Entry,5,2)||'-' ||substr(t.Date_Of_Eligibility_Entry,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Date_Of_Eligibility_Entry),
t.Claim_Status ,
t.Repricing_Status ,
t.MCS_Claim_Number ,
t.Casepac_Case_Number ,
t.Precert_Number ,
t.Referral_Number ,
t.Alternate_Id_1 ,
t.Alternate_Id_2 ,
t.Alternate_Id_3 ,
t.Input_By ,
--CASE CLAIMS.ISDATECHECK(t.Paid_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Paid_Date) when '' then null when ' ' then null else date(substr(t.Paid_Date,1,4)||'-' ||substr(t.Paid_Date,5,2)||'-' ||substr(t.Paid_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Paid_Date),
--CASE CLAIMS.ISDATECHECK(t.Input_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Input_Date) when '' then null when ' ' then null else date(substr(t.Input_Date,1,4)||'-' ||substr(t.Input_Date,5,2)||'-' ||substr(t.Input_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Input_Date),
--CASE CLAIMS.ISDATECHECK(t.Received_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Received_Date) when '' then null when ' ' then null else date(substr(t.Received_Date,1,4)||'-' ||substr(t.Received_Date,5,2)||'-' ||substr(t.Received_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Received_Date),
--CASE CLAIMS.ISDATECHECK(t.Date_sent_to_PPO_for_pricing) WHEN 0 THEN NULL ELSE case ltrim(t.Date_sent_to_PPO_for_pricing) when '' then null when ' ' then null else date(substr(t.Date_sent_to_PPO_for_pricing,1,4)||'-' ||substr(t.Date_sent_to_PPO_for_pricing,5,2)||'-' ||substr(t.Date_sent_to_PPO_for_pricing,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Date_sent_to_PPO_for_pricing),
--CASE CLAIMS.ISDATECHECK(t.Incurred_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Incurred_Date) when '' then null when ' ' then null else date(substr(t.Incurred_Date,1,4)||'-' ||substr(t.Incurred_Date,5,2)||'-' ||substr(t.Incurred_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Incurred_Date),
t.Plan_Year ,
t.Deductible_Year ,
t.Changed_By ,
--CASE CLAIMS.ISDATECHECK(t.Changed_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Changed_Date) when '' then null when ' ' then null else date(substr(t.Changed_Date,1,4)||'-' ||substr(t.Changed_Date,5,2)||'-' ||substr(t.Changed_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Changed_Date),
--CASE CLAIMS.ISDATECHECK(t.Processed_Date) WHEN 0 THEN NULL ELSE case ltrim(t.Processed_Date) when '' then null when ' ' then null else date(substr(t.Processed_Date,1,4)||'-' ||substr(t.Processed_Date,5,2)||'-' ||substr(t.Processed_Date,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Processed_Date),
t.Diagnosis_Payment_Group ,
t.ICD9_Diagnosis_Code_1 ,
t.ICD9_Diagnosis_Code_2 ,
t.ICD9_Diagnosis_Code_3 ,
t.ICD9_Diagnosis_Code_4 ,
t.Diagnosis_Category ,
t.DRG_Number ,
t.Number_of_Providers_on_claim ,
t.Key_to_Provider_File_1 ,
t.Key_to_Provider_File_2 ,
t.Key_to_Provider_File_3 ,
t.Key_to_Provider_File_4 ,
t.Provider_Tax_Id_1 ,
t.Provider_Tax_Id_2 ,
t.Provider_Tax_Id_3 ,
t.Provider_Tax_Id_4 ,
t.Provider_Account_Number_1 ,
t.Provider_Account_Number_2 ,
t.Provider_Account_Number_3 ,
t.Provider_Account_Number_4 ,
t.Network_Code_Used_1 ,
t.Network_Code_Used_2 ,
t.Network_Code_Used_3 ,
t.Network_Code_Used_4 ,
t.Penalty_Plan_Used_1 ,
t.Penalty_Plan_Used_2 ,
t.Penalty_Plan_Used_3 ,
t.Penalty_Plan_Used_4 ,
t.Checking_Account_Used_1 ,
t.Checking_Account_Used_2 ,
t.Checking_Account_Used_3 ,
t.Checking_Account_Used_4 ,
t.Checking_Account_Used_5 ,
t.Check_Number_Used_1 ,
t.Check_Number_Used_2 ,
t.Check_Number_Used_3 ,
t.Check_Number_Used_4 ,
t.Check_Number_Used_5 ,
--case rtrim(t.Net_Payment_Amount_1) when '' then Null else decimal(rtrim(t.Net_Payment_Amount_1),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Net_Payment_Amount_1),
--case rtrim(t.Net_Payment_Amount_2) when '' then Null else decimal(rtrim(t.Net_Payment_Amount_2),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Net_Payment_Amount_2),
--case rtrim(t.Net_Payment_Amount_3) when '' then Null else decimal(rtrim(t.Net_Payment_Amount_3),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Net_Payment_Amount_3),
--case rtrim(t.Net_Payment_Amount_4) when '' then Null else decimal(rtrim(t.Net_Payment_Amount_4),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Net_Payment_Amount_4),
--case rtrim(t.Net_Payment_Amount_5) when '' then Null else decimal(rtrim(t.Net_Payment_Amount_5),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Net_Payment_Amount_5),
--case rtrim(t.Adjustment_Amount_1) when '' then Null else decimal(rtrim(t.Adjustment_Amount_1),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Adjustment_Amount_1),
--case rtrim(t.Adjustment_Amount_2) when '' then Null else decimal(rtrim(t.Adjustment_Amount_2),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Adjustment_Amount_2),
--case rtrim(t.Adjustment_Amount_3) when '' then Null else decimal(rtrim(t.Adjustment_Amount_3),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Adjustment_Amount_3),
--case rtrim(t.Adjustment_Amount_4) when '' then Null else decimal(rtrim(t.Adjustment_Amount_4),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Adjustment_Amount_4),
--case rtrim(t.Adjustment_Amount_5) when '' then Null else decimal(rtrim(t.Adjustment_Amount_5),11,2) end,
dbo.ufn_Convert_to_Decimal(t.Adjustment_Amount_5),
t.Number_of_Service_Lines_Used ,
t.Charge_Amount ,
t.Total_Disallowed ,
t.Total_Ineligible_Amount ,
t.total_Copayment_Amount ,
t.Total_Over_Usual_Customary ,
t.Total_Provider_Discount_amount ,
t.Total_Original_Discount_amount ,
t.Total_Deductible ,
t.Total_Penalty_Amount ,
t.Total_Not_Covered_Amount ,
t.Total_Coinsurance ,
t.Total_Outof_Pocket ,
t.Total_Patient_Resp_Amount ,
t.Total_Claim_Paid_Amount,
t.Paid_to_Providers1,
t.Paid_to_Providers2,
t.Paid_to_Providers3,
t.Paid_to_Providers4,
t.Paid_to_Employee ,
t.COB_LEVEL_APPLIED_FLAG ,
--case rtrim(t.COB_SAVINGS) when '' then Null else decimal(rtrim(t.COB_SAVINGS),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_SAVINGS),
t.COB_ALLOWED_NOT_PAID,
--case rtrim(t.COB_Adjustment_1 ) when '' then Null else decimal(rtrim(t.COB_Adjustment_1 ),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_Adjustment_1),
--case rtrim(t.COB_Adjustment_2 ) when '' then Null else decimal(rtrim(t.COB_Adjustment_2 ),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_Adjustment_2),
--case rtrim(t.COB_Adjustment_3 ) when '' then Null else decimal(rtrim(t.COB_Adjustment_3 ),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_Adjustment_3),
--case rtrim(t.COB_Adjustment_4 ) when '' then Null else decimal(rtrim(t.COB_Adjustment_4 ),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_Adjustment_4),
--case rtrim(t.COB_Adjustment_5 ) when '' then Null else decimal(rtrim(t.COB_Adjustment_5 ),11,2) end,
dbo.ufn_Convert_to_Decimal(t.COB_Adjustment_5),
t.TYPE_COB ,
t.CR_RESERVE_ALLOWED_NOT_PAID ,
t.CR_RESERVE_ALLOWED_AMOUNT ,
t.CR_RESERVE_SAVINGS_AMOUNT ,
t.CR_RESERVE_COB_CREDITS ,
t.OTHER_INSURANCE_PAID ,
t.UPDATE_COB_TO_ACCUMS ,
t.Claims_Product_Code ,
--t.Policy_File_Key_used_1 ,
--t.Policy_File_Key_used_2 ,
--t.Policy_File_Key_used_3 ,
--t.Policy_File_Key_used_4 ,
--t.Policy_File_Key_used_5 ,
--t.Class_Code_Used ,
SUBSTRING(t.Plan_Code_Used,1,9) ,
t.Claim_Source ,
'',
t.EOB_Message_Key ,
t.Claim_Remarks_1 ,
t.Claim_Remarks_2 ,
t.Pended_Reason_Code ,
t.Hold_claim_from_Payment ,
t.Hold_claim_for_Stop_Loss ,
t.Claim_Reserved_by_Endday ,
t.Tooth_Chart_Information ,
t.Network_Ind_Deductible_Met ,
t.Network_Family_Deductible_Met ,
t.Network_Ind_Deduct_Maximum ,
t.Network_Family_Deduct_Maximum ,
t.Network_Ind_Out_Pocket_Met ,
t.Network_Family_Out_Pocket_Met ,
t.Network_Ind_Outpkt_Maximum ,
t.Network_Family_Outpkt_Maximum,
t.Claim_CONVERT ,
t.Claim_CNVACC ,
--CASE CLAIMS.ISDATECHECK(t.Claim_CNVDate) WHEN 0 THEN NULL ELSE case (t.Claim_CNVDate) when '' then null when ' ' then null else date(substr(t.Claim_CNVDate,1,4)||'-' ||substr(t.Claim_CNVDate,5,2)||'-' ||substr(t.Claim_CNVDate,7,2)) end END,
dbo.ufn_Convert_to_Date(t.Claim_CNVDate),
t.Claim_CNV1099 ,
t.Claim_chgdate_form_type ,
t.Claim_num_connection_1 ,
t.Claim_num_connection_2 ,
t.Claim_num_connection_3 ,
t.Claim_num_connection_4 ,
0 ,
0 ,
0 ,
0 ,
t.Claim_NETWORK_USED_KEY_1 ,
t.Claim_NETWORK_USED_KEY_2 ,
t.Claim_NETWORK_USED_KEY_3 ,
t.Claim_NETWORK_USED_KEY_4 ,
t.Claim_PCERT_obtained_1 ,
t.Claim_PCERT_obtained_2 ,
t.Claim_PCERT_obtained_3 ,
t.Claim_PCERT_obtained_4 ,
t.Claim_PCERT_obtained_5 ,
t.Claim_TIFF_IND ,
t.Claim_MAILCODE ,
t.Claim_TAXTYPE_Used ,
GetDate(),
--case substr(t.claim_overflag,1,1) when ' ' then '' else '1' end ,
IIF(SUBSTRING(t.claim_overflag,1,1) = ' ','','1'),
--case ltrim(t.Plan_Effective_Date) when '' then null when ' ' then null else date(substr(t.Plan_Effective_Date,1,4)||'-' ||substr(t.Plan_Effective_Date,5,2)||'-' ||substr(t.Plan_Effective_Date,7,2)) end,
dbo.ufn_Convert_to_Date(t.Plan_Effective_Date),
t.CLAIM_PLNFILL ,
t.Standard_Ind_Deductible_Met ,
t.Standard_Family_Deductible_Met ,
t.Standard_Ind_Deduct_Maximum ,
t.Standard_Family_Deduct_Maximum ,
t.Standard_Ind_Out_pocket_Met ,
t.Standard_Family_Out_pocket_Met ,
t.Standard_Ind_Outpkt_Maximum ,
t.Standard_Family_Outpkt_Maximum ,
t.CLAIM_ADJ_REASON_CODE ,
t.CLAIM_ADJUST ,
t.MANUAL_WORKFLOW_QUEUE ,
--t.CLAIM_INC_DATE ,
t.CLAIM_UB92PROC_1 ,
t.CLAIM_UB92PROC_2 ,
t.CLAIM_UB92PROC_3 ,
t.CLAIM_UB92PROC_4 ,
t.CLAIM_UB92PROC_5 ,
t.CLAIM_UB92PROC_6 ,
t.CLAIM_VERSION ,
t.CLAIM_ALTPAYID ,
t.CLAIM_ALTPAYFG ,
t.CLAIM_HCISENT ,
t.CLAIM_PX_CAT_KEY ,
t.CLAIM_PER_OCC_ACC_EVENT ,
t.CLAIM_REFERAL ,
t.CLAIM_REFSCHD,
t.CLAIM_DVISITS ,
t.CLAIM_ACEVYR ,
t.CLAIM_REFSCHD ,
t.CLAIM_ACEVYR ,
--t.CLAIM_FILLER,
--t.Dirigo_Savings_Offset_Premiums,
--t.AMPS_Out_of_Network_Negotiated,
--t.Paid_by_Stop_Loss_Carrier,
--t.Claim_not_allowed_check_run,
--t.Account_Type
t.ALLOWED_VISITS,
--t.AMPS_OO_NETWORK_NEGOTIATED_2,
--t.PAID_BY_STOPLOSS_2,
--t.HLDGRP_PAID2,
--t.ACCOUNT_TYPE_2,
t.LFSA_PROD,
t.EFT_CHECK1,
t.EFT_CHECK2,
t.EFT_CHECK3,
t.EFT_CHECK4,
t.EFT_CHECK5,
t.PMCS_INDICATOR,
t.PMCS_CLAIM_ID,
--CASE CLAIMS.ISDATECHECK(t.PMCS_DUE_DATE) WHEN 0 THEN NULL ELSE case (t.PMCS_DUE_DATE) when '' then null when ' ' then null else date(substr(t.PMCS_DUE_DATE,1,4)||'-' ||substr(t.PMCS_DUE_DATE,5,2)||'-' ||substr(t.PMCS_DUE_DATE,7,2)) end END,
dbo.ufn_Convert_to_Date(t.PMCS_DUE_DATE),
t.ORIG_PAYMENT_FOR_PMCS_ADJ,
t.ICD_CODE_1,
t.ICD_CODE_2,
t.ICD_CODE_3,
t.ICD_CODE_4,
t.ICD_CODE_5,
t.ICD_CODE_6,
t.ICD_CODE_7,
t.ICD_CODE_8,
t.ICD_VERSION,
t.CLAIM_VENDOR,
t.VENDOR_CHECK,
t.EPAY,
t.OOP_ACCUMULATOR,
t.DED_ACCUMULATOR,
t.EPAY_835
from claims.DBO.MFELDOPAIDNEW  t

--ROLLBACK

--BEGIN TRAN
INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_1,
t.Benefit_Category_1,
--case ltrim(t.From_Date_of_Service_1) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_1,1,4)||'-' ||substr(t.From_Date_of_Service_1,5,2)||'-' ||substr(t.From_Date_of_Service_1,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_1),
--case ltrim(t.Thru_Date_of_Service_1) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_1,1,4)||'-' ||substr(t.Thru_Date_of_Service_1,5,2)||'-' ||substr(t.Thru_Date_of_Service_1,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_1),
t.MCS_Denied_Reason_1,
t.Place_of_Service_1,
t.Type_of_Service_1,
t.ICD9_NEW_Pointer_1,			--t.ICD9_Pointer_1,
--decimal(t.Charge_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_1),
--decimal(t.Total_Disallowed_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_1),
--decimal(t.Ineligible_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_1),
--decimal(t.Copayment_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_1),
--decimal(t.Discount_amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_1),
--decimal(t.Deductible_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_1),
--decimal(t.Over_Usual_Customary_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_1),
--decimal(t.Denied_by_MCS_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_1),
--decimal(t.Penalty_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_1),
--decimal(t.Other_User_Defined_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_1),
t.Claim_Count_1,
t.Number_of_Service_Days_1,
--decimal(t.out_of_Pocket_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_1),
--decimal(t.Patient_Responsibility_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_1),
t.Anesthesia_Minutes_1,
t.Provider_of_Service_ptr_1,
t.CoInsurance_Percentage_1,
--decimal(t.Payment_amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_1),
--decimal(t.Paid_to_Provider_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_1),
--decimal(t.Paid_to_Patient_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_1),
--decimal(t.Withhold_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_1),
--decimal(t.Capitated_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_1),
t.Capitation_Account_1,
t.National_Drug_Code_1,
t.NDC_1,
t.Procedure_Code_1,
t.Modifiers1_1,
t.Modifiers2_1,
t.Modifiers3_1,
t.Billed_Procedure_1,
t.Ineligible_Reason_Code_1,
t.Over_UC_Reason_Code_1,
t.Discount_Reason_Code_1,
t.Copayment_Reason_Code_1,
t.Denied_by_MCS_Reason_Code_1,
t.Penalty_Reason_Code_1,
t.Not_Covered_Oth_Reason_Code_1,
t.Deductible_Accum_bucket_1,
t.OutofPocket_Accum_bucket_1,
t.OutofPocket_type_1,
t.Benefit_Exception_Bucket_1,
t.CoPayment_accum_Bucket_1,
t.History_Bucket_Pointer_1,
t.History_Entry_Pointer_1,
t.MCS_Claim_Line_1,
t.Rollover_Occured_1,
t.Copayments_Taken_1,
--decimal(t.Amount_Denied_by_MCS_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_1),
t.Where_amount_shoud_apply_1,
t.Type_COB_1,
--decimal(t.COB_amount_Employee_1,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_1),
--decimal(t.COB_amount_Provider_1,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_1),
--decimal(t.Cr_Rsrv_Allow_not_paid_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_1),
--decimal(t.Cr_Rsrv_Allow_amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_1),
--decimal(t.Cr_Rsrv_Savings_Amount_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_1),
--decimal(t.Cr_Rsrv_COB_Credits_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_1),
--decimal(t.Other_Insurance_Paid_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_1),
t.Update_COB_to_accums_1,
t.Benefit_Accum_Event_Id_1,
t.Revenue_Code_1,
--decimal(t.Surcharge_Added_to_claim_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_1),
--decimal(t.Tax_to_be_paid_on_claim_1,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_1),
t.STATE_SURCHARGE_PAID_TO_1,
t.ORIG_CODE_FOR_SUPP_1,
t.DISALLOWED_VISITS_1,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_1,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_1),
t.SERVICE_LINE_FILLER_1,
GetDate(),
--t.Emergency_Indicator_1,
t.Modifiers4_1, 
t.icd9_new_pointer_1,
t.claim_units_1,
t.line_item_1
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_1,1,1)<>' '


--BEGIN TRAN
INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_2,
t.Benefit_Category_2,
--case ltrim(t.From_Date_of_Service_2) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_2,1,4)||'-' ||substr(t.From_Date_of_Service_2,5,2)||'-' ||substr(t.From_Date_of_Service_2,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_2),
--case ltrim(t.Thru_Date_of_Service_2) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_2,1,4)||'-' ||substr(t.Thru_Date_of_Service_2,5,2)||'-' ||substr(t.Thru_Date_of_Service_2,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_2),
t.MCS_Denied_Reason_2,
t.Place_of_Service_2,
t.Type_of_Service_2,
t.ICD9_NEW_Pointer_2,			--t.ICD9_Pointer_2,
--decimal(t.Charge_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_2),
--decimal(t.Total_Disallowed_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_2),
--decimal(t.Ineligible_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_2),
--decimal(t.Copayment_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_2),
--decimal(t.Discount_amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_2),
--decimal(t.Deductible_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_2),
--decimal(t.Over_Usual_Customary_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_2),
--decimal(t.Denied_by_MCS_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_2),
--decimal(t.Penalty_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_2),
--decimal(t.Other_User_Defined_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_2),
t.Claim_Count_2,
t.Number_of_Service_Days_2,
--decimal(t.out_of_Pocket_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_2),
--decimal(t.Patient_Responsibility_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_2),
t.Anesthesia_Minutes_2,
t.Provider_of_Service_ptr_2,
t.CoInsurance_Percentage_2,
--decimal(t.Payment_amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_2),
--decimal(t.Paid_to_Provider_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_2),
--decimal(t.Paid_to_Patient_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_2),
--decimal(t.Withhold_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_2),
--decimal(t.Capitated_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_2),
t.Capitation_Account_2,
t.National_Drug_Code_2,
t.NDC_2,
t.Procedure_Code_2,
t.Modifiers1_2,
t.Modifiers2_2,
t.Modifiers3_2,
t.Billed_Procedure_2,
t.Ineligible_Reason_Code_2,
t.Over_UC_Reason_Code_2,
t.Discount_Reason_Code_2,
t.Copayment_Reason_Code_2,
t.Denied_by_MCS_Reason_Code_2,
t.Penalty_Reason_Code_2,
t.Not_Covered_Oth_Reason_Code_2,
t.Deductible_Accum_bucket_2,
t.OutofPocket_Accum_bucket_2,
t.OutofPocket_type_2,
t.Benefit_Exception_Bucket_2,
t.CoPayment_accum_Bucket_2,
t.History_Bucket_Pointer_2,
t.History_Entry_Pointer_2,
t.MCS_Claim_Line_2,
t.Rollover_Occured_2,
t.Copayments_Taken_2,
--decimal(t.Amount_Denied_by_MCS_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_2),
t.Where_amount_shoud_apply_2,
t.Type_COB_2,
--decimal(t.COB_amount_Employee_2,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_2),
--decimal(t.COB_amount_Provider_2,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_2),
--decimal(t.Cr_Rsrv_Allow_not_paid_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_2),
--decimal(t.Cr_Rsrv_Allow_amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_2),
--decimal(t.Cr_Rsrv_Savings_Amount_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_2),
--decimal(t.Cr_Rsrv_COB_Credits_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_2),
--decimal(t.Other_Insurance_Paid_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_2),
t.Update_COB_to_accums_2,
t.Benefit_Accum_Event_Id_2,
t.Revenue_Code_2,
--decimal(t.Surcharge_Added_to_claim_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_2),
--decimal(t.Tax_to_be_paid_on_claim_2,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_2),
t.STATE_SURCHARGE_PAID_TO_2,
t.ORIG_CODE_FOR_SUPP_2,
t.DISALLOWED_VISITS_2,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_2,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_2),
t.SERVICE_LINE_FILLER_2,
GetDate(),
--t.Emergency_Indicator_2,
t.Modifiers4_2, 
t.icd9_new_pointer_2,
t.claim_units_2,
t.line_item_2
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_2,1,1)<>' '

--ROLLBACK


--BEGIN TRAN
INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_3,
t.Benefit_Category_3,
--case ltrim(t.From_Date_of_Service_3) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_3,1,4)||'-' ||substr(t.From_Date_of_Service_3,5,2)||'-' ||substr(t.From_Date_of_Service_3,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_3),
--case ltrim(t.Thru_Date_of_Service_3) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_3,1,4)||'-' ||substr(t.Thru_Date_of_Service_3,5,2)||'-' ||substr(t.Thru_Date_of_Service_3,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_3),
t.MCS_Denied_Reason_3,
t.Place_of_Service_3,
t.Type_of_Service_3,
t.ICD9_NEW_Pointer_3,			--t.ICD9_Pointer_3,
--decimal(t.Charge_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_3),
--decimal(t.Total_Disallowed_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_3),
--decimal(t.Ineligible_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_3),
--decimal(t.Copayment_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_3),
--decimal(t.Discount_amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_3),
--decimal(t.Deductible_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_3),
--decimal(t.Over_Usual_Customary_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_3),
--decimal(t.Denied_by_MCS_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_3),
--decimal(t.Penalty_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_3),
--decimal(t.Other_User_Defined_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_3),
t.Claim_Count_3,
t.Number_of_Service_Days_3,
--decimal(t.out_of_Pocket_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_3),
--decimal(t.Patient_Responsibility_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_3),
t.Anesthesia_Minutes_3,
t.Provider_of_Service_ptr_3,
t.CoInsurance_Percentage_3,
--decimal(t.Payment_amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_3),
--decimal(t.Paid_to_Provider_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_3),
--decimal(t.Paid_to_Patient_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_3),
--decimal(t.Withhold_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_3),
--decimal(t.Capitated_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_3),
t.Capitation_Account_3,
t.National_Drug_Code_3,
t.NDC_3,
t.Procedure_Code_3,
t.Modifiers1_3,
t.Modifiers2_3,
t.Modifiers3_3,
t.Billed_Procedure_3,
t.Ineligible_Reason_Code_3,
t.Over_UC_Reason_Code_3,
t.Discount_Reason_Code_3,
t.Copayment_Reason_Code_3,
t.Denied_by_MCS_Reason_Code_3,
t.Penalty_Reason_Code_3,
t.Not_Covered_Oth_Reason_Code_3,
t.Deductible_Accum_bucket_3,
t.OutofPocket_Accum_bucket_3,
t.OutofPocket_type_3,
t.Benefit_Exception_Bucket_3,
t.CoPayment_accum_Bucket_3,
t.History_Bucket_Pointer_3,
t.History_Entry_Pointer_3,
t.MCS_Claim_Line_3,
t.Rollover_Occured_3,
t.Copayments_Taken_3,
--decimal(t.Amount_Denied_by_MCS_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_3),
t.Where_amount_shoud_apply_3,
t.Type_COB_3,
--decimal(t.COB_amount_Employee_3,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_3),
--decimal(t.COB_amount_Provider_3,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_3),
--decimal(t.Cr_Rsrv_Allow_not_paid_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_3),
--decimal(t.Cr_Rsrv_Allow_amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_3),
--decimal(t.Cr_Rsrv_Savings_Amount_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_3),
--decimal(t.Cr_Rsrv_COB_Credits_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_3),
--decimal(t.Other_Insurance_Paid_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_3),
t.Update_COB_to_accums_3,
t.Benefit_Accum_Event_Id_3,
t.Revenue_Code_3,
--decimal(t.Surcharge_Added_to_claim_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_3),
--decimal(t.Tax_to_be_paid_on_claim_3,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_3),
t.STATE_SURCHARGE_PAID_TO_3,
t.ORIG_CODE_FOR_SUPP_3,
t.DISALLOWED_VISITS_3,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_3,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_3),
t.SERVICE_LINE_FILLER_3,
GetDate(),
--t.Emergency_Indicator_3,
t.Modifiers4_3, 
t.icd9_new_pointer_3,
t.claim_units_3,
t.line_item_3
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_3,1,1)<>' '


--ROLLBACK


--BEGIN TRAN
INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_4,
t.Benefit_Category_4,
--case ltrim(t.From_Date_of_Service_4) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_4,1,4)||'-' ||substr(t.From_Date_of_Service_4,5,2)||'-' ||substr(t.From_Date_of_Service_4,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_4),
--case ltrim(t.Thru_Date_of_Service_4) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_4,1,4)||'-' ||substr(t.Thru_Date_of_Service_4,5,2)||'-' ||substr(t.Thru_Date_of_Service_4,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_4),
t.MCS_Denied_Reason_4,
t.Place_of_Service_4,
t.Type_of_Service_4,
t.ICD9_NEW_Pointer_4,			--t.ICD9_Pointer_4,
--decimal(t.Charge_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_4),
--decimal(t.Total_Disallowed_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_4),
--decimal(t.Ineligible_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_4),
--decimal(t.Copayment_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_4),
--decimal(t.Discount_amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_4),
--decimal(t.Deductible_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_4),
--decimal(t.Over_Usual_Customary_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_4),
--decimal(t.Denied_by_MCS_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_4),
--decimal(t.Penalty_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_4),
--decimal(t.Other_User_Defined_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_4),
t.Claim_Count_4,
t.Number_of_Service_Days_4,
--decimal(t.out_of_Pocket_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_4),
--decimal(t.Patient_Responsibility_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_4),
t.Anesthesia_Minutes_4,
t.Provider_of_Service_ptr_4,
t.CoInsurance_Percentage_4,
--decimal(t.Payment_amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_4),
--decimal(t.Paid_to_Provider_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_4),
--decimal(t.Paid_to_Patient_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_4),
--decimal(t.Withhold_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_4),
--decimal(t.Capitated_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_4),
t.Capitation_Account_4,
t.National_Drug_Code_4,
t.NDC_4,
t.Procedure_Code_4,
t.Modifiers1_4,
t.Modifiers2_4,
t.Modifiers3_4,
t.Billed_Procedure_4,
t.Ineligible_Reason_Code_4,
t.Over_UC_Reason_Code_4,
t.Discount_Reason_Code_4,
t.Copayment_Reason_Code_4,
t.Denied_by_MCS_Reason_Code_4,
t.Penalty_Reason_Code_4,
t.Not_Covered_Oth_Reason_Code_4,
t.Deductible_Accum_bucket_4,
t.OutofPocket_Accum_bucket_4,
t.OutofPocket_type_4,
t.Benefit_Exception_Bucket_4,
t.CoPayment_accum_Bucket_4,
t.History_Bucket_Pointer_4,
t.History_Entry_Pointer_4,
t.MCS_Claim_Line_4,
t.Rollover_Occured_4,
t.Copayments_Taken_4,
--decimal(t.Amount_Denied_by_MCS_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_4),
t.Where_amount_shoud_apply_4,
t.Type_COB_4,
--decimal(t.COB_amount_Employee_4,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_4),
--decimal(t.COB_amount_Provider_4,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_4),
--decimal(t.Cr_Rsrv_Allow_not_paid_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_4),
--decimal(t.Cr_Rsrv_Allow_amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_4),
--decimal(t.Cr_Rsrv_Savings_Amount_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_4),
--decimal(t.Cr_Rsrv_COB_Credits_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_4),
--decimal(t.Other_Insurance_Paid_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_4),
t.Update_COB_to_accums_4,
t.Benefit_Accum_Event_Id_4,
t.Revenue_Code_4,
--decimal(t.Surcharge_Added_to_claim_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_4),
--decimal(t.Tax_to_be_paid_on_claim_4,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_4),
t.STATE_SURCHARGE_PAID_TO_4,
t.ORIG_CODE_FOR_SUPP_4,
t.DISALLOWED_VISITS_4,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_4,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_4),
t.SERVICE_LINE_FILLER_4,
GetDate(),
--t.Emergency_Indicator_4,
t.Modifiers4_4, 
t.icd9_new_pointer_4,
t.claim_units_4,
t.line_item_4
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_4,1,1)<>' '


INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_5,
t.Benefit_Category_5,
--case ltrim(t.From_Date_of_Service_5) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_5,1,4)||'-' ||substr(t.From_Date_of_Service_5,5,2)||'-' ||substr(t.From_Date_of_Service_5,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_5),
--case ltrim(t.Thru_Date_of_Service_5) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_5,1,4)||'-' ||substr(t.Thru_Date_of_Service_5,5,2)||'-' ||substr(t.Thru_Date_of_Service_5,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_5),
t.MCS_Denied_Reason_5,
t.Place_of_Service_5,
t.Type_of_Service_5,
t.ICD9_NEW_Pointer_5,			--t.ICD9_Pointer_5,
--decimal(t.Charge_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_5),
--decimal(t.Total_Disallowed_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_5),
--decimal(t.Ineligible_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_5),
--decimal(t.Copayment_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_5),
--decimal(t.Discount_amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_5),
--decimal(t.Deductible_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_5),
--decimal(t.Over_Usual_Customary_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_5),
--decimal(t.Denied_by_MCS_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_5),
--decimal(t.Penalty_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_5),
--decimal(t.Other_User_Defined_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_5),
t.Claim_Count_5,
t.Number_of_Service_Days_5,
--decimal(t.out_of_Pocket_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_5),
--decimal(t.Patient_Responsibility_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_5),
t.Anesthesia_Minutes_5,
t.Provider_of_Service_ptr_5,
t.CoInsurance_Percentage_5,
--decimal(t.Payment_amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_5),
--decimal(t.Paid_to_Provider_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_5),
--decimal(t.Paid_to_Patient_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_5),
--decimal(t.Withhold_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_5),
--decimal(t.Capitated_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_5),
t.Capitation_Account_5,
t.National_Drug_Code_5,
t.NDC_5,
t.Procedure_Code_5,
t.Modifiers1_5,
t.Modifiers2_5,
t.Modifiers3_5,
t.Billed_Procedure_5,
t.Ineligible_Reason_Code_5,
t.Over_UC_Reason_Code_5,
t.Discount_Reason_Code_5,
t.Copayment_Reason_Code_5,
t.Denied_by_MCS_Reason_Code_5,
t.Penalty_Reason_Code_5,
t.Not_Covered_Oth_Reason_Code_5,
t.Deductible_Accum_bucket_5,
t.OutofPocket_Accum_bucket_5,
t.OutofPocket_type_5,
t.Benefit_Exception_Bucket_5,
t.CoPayment_accum_Bucket_5,
t.History_Bucket_Pointer_5,
t.History_Entry_Pointer_5,
t.MCS_Claim_Line_5,
t.Rollover_Occured_5,
t.Copayments_Taken_5,
--decimal(t.Amount_Denied_by_MCS_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_5),
t.Where_amount_shoud_apply_5,
t.Type_COB_5,
--decimal(t.COB_amount_Employee_5,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_5),
--decimal(t.COB_amount_Provider_5,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_5),
--decimal(t.Cr_Rsrv_Allow_not_paid_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_5),
--decimal(t.Cr_Rsrv_Allow_amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_5),
--decimal(t.Cr_Rsrv_Savings_Amount_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_5),
--decimal(t.Cr_Rsrv_COB_Credits_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_5),
--decimal(t.Other_Insurance_Paid_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_5),
t.Update_COB_to_accums_5,
t.Benefit_Accum_Event_Id_5,
t.Revenue_Code_5,
--decimal(t.Surcharge_Added_to_claim_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_5),
--decimal(t.Tax_to_be_paid_on_claim_5,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_5),
t.STATE_SURCHARGE_PAID_TO_5,
t.ORIG_CODE_FOR_SUPP_5,
t.DISALLOWED_VISITS_5,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_5,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_5),
t.SERVICE_LINE_FILLER_5,
GetDate(),
--t.Emergency_Indicator_5,
t.Modifiers4_5, 
t.icd9_new_pointer_5,
t.claim_units_5,
t.line_item_5
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_5,1,1)<>' '


INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_6,
t.Benefit_Category_6,
--case ltrim(t.From_Date_of_Service_6) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_6,1,4)||'-' ||substr(t.From_Date_of_Service_6,5,2)||'-' ||substr(t.From_Date_of_Service_6,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_6),
--case ltrim(t.Thru_Date_of_Service_6) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_6,1,4)||'-' ||substr(t.Thru_Date_of_Service_6,5,2)||'-' ||substr(t.Thru_Date_of_Service_6,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_6),
t.MCS_Denied_Reason_6,
t.Place_of_Service_6,
t.Type_of_Service_6,
t.ICD9_NEW_Pointer_6,			--t.ICD9_Pointer_6,
--decimal(t.Charge_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_6),
--decimal(t.Total_Disallowed_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_6),
--decimal(t.Ineligible_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_6),
--decimal(t.Copayment_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_6),
--decimal(t.Discount_amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_6),
--decimal(t.Deductible_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_6),
--decimal(t.Over_Usual_Customary_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_6),
--decimal(t.Denied_by_MCS_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_6),
--decimal(t.Penalty_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_6),
--decimal(t.Other_User_Defined_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_6),
t.Claim_Count_6,
t.Number_of_Service_Days_6,
--decimal(t.out_of_Pocket_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_6),
--decimal(t.Patient_Responsibility_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_6),
t.Anesthesia_Minutes_6,
t.Provider_of_Service_ptr_6,
t.CoInsurance_Percentage_6,
--decimal(t.Payment_amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_6),
--decimal(t.Paid_to_Provider_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_6),
--decimal(t.Paid_to_Patient_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_6),
--decimal(t.Withhold_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_6),
--decimal(t.Capitated_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_6),
t.Capitation_Account_6,
t.National_Drug_Code_6,
t.NDC_6,
t.Procedure_Code_6,
t.Modifiers1_6,
t.Modifiers2_6,
t.Modifiers3_6,
t.Billed_Procedure_6,
t.Ineligible_Reason_Code_6,
t.Over_UC_Reason_Code_6,
t.Discount_Reason_Code_6,
t.Copayment_Reason_Code_6,
t.Denied_by_MCS_Reason_Code_6,
t.Penalty_Reason_Code_6,
t.Not_Covered_Oth_Reason_Code_6,
t.Deductible_Accum_bucket_6,
t.OutofPocket_Accum_bucket_6,
t.OutofPocket_type_6,
t.Benefit_Exception_Bucket_6,
t.CoPayment_accum_Bucket_6,
t.History_Bucket_Pointer_6,
t.History_Entry_Pointer_6,
t.MCS_Claim_Line_6,
t.Rollover_Occured_6,
t.Copayments_Taken_6,
--decimal(t.Amount_Denied_by_MCS_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_6),
t.Where_amount_shoud_apply_6,
t.Type_COB_6,
--decimal(t.COB_amount_Employee_6,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_6),
--decimal(t.COB_amount_Provider_6,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_6),
--decimal(t.Cr_Rsrv_Allow_not_paid_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_6),
--decimal(t.Cr_Rsrv_Allow_amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_6),
--decimal(t.Cr_Rsrv_Savings_Amount_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_6),
--decimal(t.Cr_Rsrv_COB_Credits_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_6),
--decimal(t.Other_Insurance_Paid_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_6),
t.Update_COB_to_accums_6,
t.Benefit_Accum_Event_Id_6,
t.Revenue_Code_6,
--decimal(t.Surcharge_Added_to_claim_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_6),
--decimal(t.Tax_to_be_paid_on_claim_6,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_6),
t.STATE_SURCHARGE_PAID_TO_6,
t.ORIG_CODE_FOR_SUPP_6,
t.DISALLOWED_VISITS_6,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_6,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_6),
t.SERVICE_LINE_FILLER_6,
GetDate(),
--t.Emergency_Indicator_6,
t.Modifiers4_6, 
t.icd9_new_pointer_6,
t.claim_units_6,
t.line_item_6
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_6,1,1)<>' '

INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_7,
t.Benefit_Category_7,
--case ltrim(t.From_Date_of_Service_7) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_7,1,4)||'-' ||substr(t.From_Date_of_Service_7,5,2)||'-' ||substr(t.From_Date_of_Service_7,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_7),
--case ltrim(t.Thru_Date_of_Service_7) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_7,1,4)||'-' ||substr(t.Thru_Date_of_Service_7,5,2)||'-' ||substr(t.Thru_Date_of_Service_7,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_7),
t.MCS_Denied_Reason_7,
t.Place_of_Service_7,
t.Type_of_Service_7,
t.ICD9_NEW_Pointer_7,			--t.ICD9_Pointer_7,
--decimal(t.Charge_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_7),
--decimal(t.Total_Disallowed_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_7),
--decimal(t.Ineligible_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_7),
--decimal(t.Copayment_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_7),
--decimal(t.Discount_amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_7),
--decimal(t.Deductible_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_7),
--decimal(t.Over_Usual_Customary_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_7),
--decimal(t.Denied_by_MCS_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_7),
--decimal(t.Penalty_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_7),
--decimal(t.Other_User_Defined_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_7),
t.Claim_Count_7,
t.Number_of_Service_Days_7,
--decimal(t.out_of_Pocket_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_7),
--decimal(t.Patient_Responsibility_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_7),
t.Anesthesia_Minutes_7,
t.Provider_of_Service_ptr_7,
t.CoInsurance_Percentage_7,
--decimal(t.Payment_amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_7),
--decimal(t.Paid_to_Provider_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_7),
--decimal(t.Paid_to_Patient_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_7),
--decimal(t.Withhold_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_7),
--decimal(t.Capitated_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_7),
t.Capitation_Account_7,
t.National_Drug_Code_7,
t.NDC_7,
t.Procedure_Code_7,
t.Modifiers1_7,
t.Modifiers2_7,
t.Modifiers3_7,
t.Billed_Procedure_7,
t.Ineligible_Reason_Code_7,
t.Over_UC_Reason_Code_7,
t.Discount_Reason_Code_7,
t.Copayment_Reason_Code_7,
t.Denied_by_MCS_Reason_Code_7,
t.Penalty_Reason_Code_7,
t.Not_Covered_Oth_Reason_Code_7,
t.Deductible_Accum_bucket_7,
t.OutofPocket_Accum_bucket_7,
t.OutofPocket_type_7,
t.Benefit_Exception_Bucket_7,
t.CoPayment_accum_Bucket_7,
t.History_Bucket_Pointer_7,
t.History_Entry_Pointer_7,
t.MCS_Claim_Line_7,
t.Rollover_Occured_7,
t.Copayments_Taken_7,
--decimal(t.Amount_Denied_by_MCS_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_7),
t.Where_amount_shoud_apply_7,
t.Type_COB_7,
--decimal(t.COB_amount_Employee_7,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_7),
--decimal(t.COB_amount_Provider_7,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_7),
--decimal(t.Cr_Rsrv_Allow_not_paid_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_7),
--decimal(t.Cr_Rsrv_Allow_amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_7),
--decimal(t.Cr_Rsrv_Savings_Amount_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_7),
--decimal(t.Cr_Rsrv_COB_Credits_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_7),
--decimal(t.Other_Insurance_Paid_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_7),
t.Update_COB_to_accums_7,
t.Benefit_Accum_Event_Id_7,
t.Revenue_Code_7,
--decimal(t.Surcharge_Added_to_claim_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_7),
--decimal(t.Tax_to_be_paid_on_claim_7,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_7),
t.STATE_SURCHARGE_PAID_TO_7,
t.ORIG_CODE_FOR_SUPP_7,
t.DISALLOWED_VISITS_7,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_7,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_7),
t.SERVICE_LINE_FILLER_7,
GetDate(),
--t.Emergency_Indicator_7,
t.Modifiers4_7, 
t.icd9_new_pointer_7,
t.claim_units_7,
t.line_item_7
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_7,1,1)<>' '


INSERT INTO Claims.DBO.ELDOCLMSLINES(
Policy_Underwriter,
Group_Number,
Claim_Number,
Employee_SSN,
Benefit_Code,
Benefit_Category,
From_Date_of_Service,
Thru_Date_of_Service,
MCS_Denied_Reason,
Place_of_Service,
Type_of_Service,
ICD9_Pointer,
Charge_Amount,
Total_Disallowed,
Ineligible_Amount,
Copayment_Amount,
Discount_amount,
Deductible_Amount,
Over_Usual_Customary,
Denied_by_MCS,
Penalty_Amount,
Other_User_Defined,
Claim_Count,
Number_of_Service_Days,
out_of_Pocket_Amount,
Patient_Responsibility,
Anesthesia_Minutes,
Provider_of_Service_ptr,
CoInsurance_Percentage,
Payment_amount,
Paid_to_Provider,
Paid_to_Patient,
Withhold_Amount,
Capitated_Amount,
Capitation_Account,
National_Drug_Code,
NDC,
Procedure_Code,
Modifiers1,
Modifiers2,
Modifiers3,
Billed_Procedure,
Ineligible_Reason_Code,
Over_UC_Reason_Code,
Discount_Reason_Code,
Copayment_Reason_Code,
Denied_by_MCS_Reason_Code,
Penalty_Reason_Code,
Not_Covered_Oth_Reason_Code,
Deductible_Accum_bucket,
OutofPocket_Accum_bucket,
OutofPocket_type,
Benefit_Exception_Bucket,
CoPayment_accum_Bucket,
History_Bucket_Pointer,
History_Entry_Pointer,
MCS_Claim_Line,
Rollover_Occured,
Copayments_Taken,
Amount_Denied_by_MCS,
Where_amount_shoud_apply,
Type_COB,
COB_amount_Employee,
COB_amount_Provider,
Cr_Rsrv_Allow_not_paid,
Cr_Rsrv_Allow_amount,
Cr_Rsrv_Savings_Amount,
Cr_Rsrv_COB_Credits,
Other_Insurance_Paid,
Update_COB_to_accums,
Benefit_Accum_Event_Id,
Revenue_Code,
Surcharge_Added_to_claim,
Tax_to_be_paid_on_claim,
STATE_SURCHARGE_PAID_TO,
ORIG_CODE_FOR_SUPP,
DISALLOWED_VISITS,
ORIG_INELG_AMT_FROM_PRICING,
SERVICE_LINE_FILLER,
load_date,
--Emergency_Indicator,
Modifiers4,
icd9_new_pointer,
claim_units,
line_item
)
select
t.Policy_Underwriter,
t.Group_Number,
t.Claim_Number,
t.Employee_SSN,
t.Benefit_Code_8,
t.Benefit_Category_8,
--case ltrim(t.From_Date_of_Service_8) when '' then null when '        ' then null else date(substr(t.From_Date_of_Service_8,1,4)||'-' ||substr(t.From_Date_of_Service_8,5,2)||'-' ||substr(t.From_Date_of_Service_8,7,2)) end,
dbo.ufn_Convert_to_Date(t.From_Date_of_Service_8),
--case ltrim(t.Thru_Date_of_Service_8) when '' then null when '        ' then null else date(substr(t.Thru_Date_of_Service_8,1,4)||'-' ||substr(t.Thru_Date_of_Service_8,5,2)||'-' ||substr(t.Thru_Date_of_Service_8,7,2)) end,
dbo.ufn_Convert_to_Date(t.Thru_Date_of_Service_8),
t.MCS_Denied_Reason_8,
t.Place_of_Service_8,
t.Type_of_Service_8,
t.ICD9_NEW_Pointer_8,			--t.ICD9_Pointer_8,
--decimal(t.Charge_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Charge_Amount_8),
--decimal(t.Total_Disallowed_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Total_Disallowed_8),
--decimal(t.Ineligible_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Ineligible_Amount_8),
--decimal(t.Copayment_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Copayment_Amount_8),
--decimal(t.Discount_amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Discount_amount_8),
--decimal(t.Deductible_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Deductible_Amount_8),
--decimal(t.Over_Usual_Customary_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Over_Usual_Customary_8),
--decimal(t.Denied_by_MCS_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Denied_by_MCS_8),
--decimal(t.Penalty_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Penalty_Amount_8),
--decimal(t.Other_User_Defined_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_User_Defined_8),
t.Claim_Count_8,
t.Number_of_Service_Days_8,
--decimal(t.out_of_Pocket_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.out_of_Pocket_Amount_8),
--decimal(t.Patient_Responsibility_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Patient_Responsibility_8),
t.Anesthesia_Minutes_8,
t.Provider_of_Service_ptr_8,
t.CoInsurance_Percentage_8,
--decimal(t.Payment_amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Payment_amount_8),
--decimal(t.Paid_to_Provider_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Provider_8),
--decimal(t.Paid_to_Patient_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Paid_to_Patient_8),
--decimal(t.Withhold_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Withhold_Amount_8),
--decimal(t.Capitated_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Capitated_Amount_8),
t.Capitation_Account_8,
t.National_Drug_Code_8,
t.NDC_8,
t.Procedure_Code_8,
t.Modifiers1_8,
t.Modifiers2_8,
t.Modifiers3_8,
t.Billed_Procedure_8,
t.Ineligible_Reason_Code_8,
t.Over_UC_Reason_Code_8,
t.Discount_Reason_Code_8,
t.Copayment_Reason_Code_8,
t.Denied_by_MCS_Reason_Code_8,
t.Penalty_Reason_Code_8,
t.Not_Covered_Oth_Reason_Code_8,
t.Deductible_Accum_bucket_8,
t.OutofPocket_Accum_bucket_8,
t.OutofPocket_type_8,
t.Benefit_Exception_Bucket_8,
t.CoPayment_accum_Bucket_8,
t.History_Bucket_Pointer_8,
t.History_Entry_Pointer_8,
t.MCS_Claim_Line_8,
t.Rollover_Occured_8,
t.Copayments_Taken_8,
--decimal(t.Amount_Denied_by_MCS_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Amount_Denied_by_MCS_8),
t.Where_amount_shoud_apply_8,
t.Type_COB_8,
--decimal(t.COB_amount_Employee_8,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Employee_8),
--decimal(t.COB_amount_Provider_8,11,2),
dbo.ufn_Convert_to_Decimal(t.COB_amount_Provider_8),
--decimal(t.Cr_Rsrv_Allow_not_paid_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_not_paid_8),
--decimal(t.Cr_Rsrv_Allow_amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Allow_amount_8),
--decimal(t.Cr_Rsrv_Savings_Amount_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_Savings_Amount_8),
--decimal(t.Cr_Rsrv_COB_Credits_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Cr_Rsrv_COB_Credits_8),
--decimal(t.Other_Insurance_Paid_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Other_Insurance_Paid_8),
t.Update_COB_to_accums_8,
t.Benefit_Accum_Event_Id_8,
t.Revenue_Code_8,
--decimal(t.Surcharge_Added_to_claim_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Surcharge_Added_to_claim_8),
--decimal(t.Tax_to_be_paid_on_claim_8,11,2),
dbo.ufn_Convert_to_Decimal(t.Tax_to_be_paid_on_claim_8),
t.STATE_SURCHARGE_PAID_TO_8,
t.ORIG_CODE_FOR_SUPP_8,
t.DISALLOWED_VISITS_8,
--decimal(t.ORIG_INELG_AMT_FROM_PRICING_8,11,2),
dbo.ufn_Convert_to_Decimal(t.ORIG_INELG_AMT_FROM_PRICING_8),
t.SERVICE_LINE_FILLER_8,
GetDate(),
--t.Emergency_Indicator_8,
t.Modifiers4_8, 
t.icd9_new_pointer_8,
t.claim_units_8,
t.line_item_8
from CLAIMS.DBO.MFELDOPAIDNEW t
where
SUBSTRING(t.Benefit_Code_8,1,1)<>' '


END TRY  
BEGIN CATCH  
   SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage;  
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;  

END CATCH; 

IF @@TRANCOUNT > 0  

    COMMIT TRANSACTION;  
  
END