-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[INSERT_MFELDOMCSCLMLINESNEW] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

BEGIN TRANSACTION; 

BEGIN TRY  

insert into claims.dbo.eldomcsclmlines(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
CLAIM_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
LINE_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
DUP_CLAIM_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
REVENUE_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DESCRIPTION,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
HCPCS_PROCEDURE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
MODIFIER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
RATE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
DATE_FROM,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
DATE_TO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
PLACE_OD_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
TYPE_OF_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
UNITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
CHARGE_AMT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
NON_COVERED,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
DIAG_POINTER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
EPSDT_FAMILY_PLAN,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
EMG,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
COB,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
RESERVED_LOCAL_USE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
WORKERS_COMP_FEE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
FEE_SCHEDULE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
OCN_PRICING_RESULTS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
DUPL_STATUS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
MESSAGE_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
ADJUST_REASON,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
CAP_ENCOUNTERED_AMT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
CAP_WITHHELD_AMT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
INCOMING_SERVICE_LINE_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
BENEFIT_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
TOOTH_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
TOOTH_SURFACCE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
TOOTH_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
CHGS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
CAP_WITHHELD_PERC,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
CAP_WITHHELD_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
UB92_UNITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ANESTHESIA_MINUTES,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
DENIED_REASON_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
POLICY_UNDERWRITER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
GROUP_NUMBER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
RPCSD_DAYS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ANES_BASE_UNITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
MSORDER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
REASON_CODE_TO_HPAC,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
UB92V5_RECORD_TYPE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
OTHER_INSURANCE_PAID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
OTHER_INSURANCE_ALLOWABLE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
OTHER_INSURANCE_DISCOUNT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
BUNDLED_FOR_CES_EDITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
RPCSLINE_SORTEDITS,
RPCSSDRATE2,
OTHER_INSURANCE,
BCBS_DENY_CODE,
DISCOUNT ,
DISCOUNT_CODE ,
COPAY ,
CARRIER_PAID,
CARRIER_DENIED,
GROUPED ,
LINE_NUMBER ,
UNITS2 ,
DIAG_POINTER2, 
POST_PRICING_FLAG
)             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
select                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
t.POLICY_UNDERWRITER + t.GROUP_NUMBER + t.CLAIM_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
ltrim(rtrim(t.LINE_NO)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
t.DUP_CLAIM_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.REVENUE_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.DESCRIPTION,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
t.HCPCS_PROCEDURE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
substring(t.MODIFIER,1,6),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
--Case when claims.ISDecimalCheck(t.RATE)=0 then 0 else Case when rtrim(ltrim(t.RATE))='.' then 0 else Case when substr(rtrim(ltrim(t.RATE)),1,1)='-' then -1 * Decimal(Replace(t.RATE,'-',''),12,2) else Decimal(t.RATE,12,2) end end end,
dbo.ufn_Convert_to_Decimal(t.RATE),
--case ltrim(t.Date_From) when '' then null when ' ' then null else date(substr(t.Date_From,1,4)||'-' ||substr(t.Date_From,5,2)||'-' ||substr(t.Date_From,7,2)) end,                                                                                                                                                                                                                                                                                                                                                                                                                                                               
dbo.ufn_Convert_to_Date(t.Date_From),
--case ltrim(t.Date_To) when '' then null when ' ' then null else date(substr(t.Date_To,1,4)||'-' ||substr(t.Date_To,5,2)||'-' ||substr(t.Date_To,7,2)) end,                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
dbo.ufn_Convert_to_Date(t.Date_To),
t.PLACE_OD_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
t.TYPE_OF_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
--Case when claims.ISDecimalCheck(t.UNITS)=0 then 0 else Case when substr(rtrim(ltrim(t.UNITS)),1,1)='-' then -1 * Decimal(Replace(t.UNITS,'-',''),12,2) else Decimal(t.UNITS,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.UNITS),
--Case when claims.ISDecimalCheck(t.CHARGE_AMT)=0 then 0 else Case when substr(rtrim(ltrim(t.CHARGE_AMT)),1,1)='-' then -1 * Decimal(Replace(t.CHARGE_AMT,'-',''),12,2) else Decimal(t.CHARGE_AMT,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.CHARGE_AMT),
--Case when claims.ISDecimalCheck(t.NON_COVERED)=0 then 0 else Case when substr(rtrim(ltrim(t.NON_COVERED)),1,1)='-' then -1 * Decimal(Replace(t.NON_COVERED,'-',''),12,2) else Decimal(t.NON_COVERED,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.NON_COVERED),
t.DIAG_POINTER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.EPSDT_FAMILY_PLAN,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
t.EMG,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
t.COB,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
t.RESERVED_LOCAL_USE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
--Case when claims.ISDecimalCheck(t.WORKERS_COMP_FEE)=0 then 0 else Case when substr(rtrim(ltrim(t.WORKERS_COMP_FEE)),1,1)='-' then -1 * Decimal(Replace(t.WORKERS_COMP_FEE,'-',''),12,2) else Decimal(t.WORKERS_COMP_FEE,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.WORKERS_COMP_FEE),
--Case when claims.ISDecimalCheck(t.FEE_SCHEDULE)=0 then 0 else Case when substr(rtrim(ltrim(t.FEE_SCHEDULE)),1,1)='-' then -1 * Decimal(Replace(t.FEE_SCHEDULE,'-',''),12,2) else Decimal(t.FEE_SCHEDULE,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.FEE_SCHEDULE),
t.OCN_PRICING_RESULTS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
'',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
t.MESSAGE_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.ADJUST_REASON,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
--Case when claims.ISDecimalCheck(t.CAP_ENCOUNTERED_AMT)=0 then 0 else Case when substr(rtrim(ltrim(t.CAP_ENCOUNTERED_AMT)),1,1)='-' then -1 * Decimal(Replace(t.CAP_ENCOUNTERED_AMT,'-',''),12,2) else Decimal(t.CAP_ENCOUNTERED_AMT,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.CAP_ENCOUNTERED_AMT),
--Case when claims.ISDecimalCheck(t.CAP_WITHHELD_AMT)=0 then 0 else Case when substr(rtrim(ltrim(t.CAP_WITHHELD_AMT)),1,1)='-' then -1 * Decimal(Replace(t.CAP_WITHHELD_AMT,'-',''),12,2) else Decimal(t.CAP_WITHHELD_AMT,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.CAP_WITHHELD_AMT),
t.INCOMING_SERVICE_LINE_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
t.BENEFIT_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.TOOTH_NO,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
t.TOOTH_SURFACCE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
t.TOOTH_SERVICE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
t.CAP_WITHHELD_PERC,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
t.CAP_WITHHELD_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
t.ANESTHESIA_MINUTES,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
t.DENIED_REASON_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
t.POLICY_UNDERWRITER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
t.GROUP_NUMBER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
t.RPCSD_DAYS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
t.ANES_BASE_UNITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
t.MSORDER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
t.REASON_CODE_TO_HPAC,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
t.UB92V5_RECORD_TYPE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
--Case when claims.ISDecimalCheck(t.OTHER_INSURANCE_PAID)=0 then 0 else Case when substr(rtrim(ltrim(t.OTHER_INSURANCE_PAID)),1,1)='-' then -1 * Decimal(Replace(t.OTHER_INSURANCE_PAID,'-',''),12,2) else Decimal(t.OTHER_INSURANCE_PAID,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.OTHER_INSURANCE_PAID),
--Case when claims.ISDecimalCheck(t.OTHER_INSURANCE_ALLOWABLE)=0 then 0 else Case when substr(rtrim(ltrim(t.OTHER_INSURANCE_ALLOWABLE)),1,1)='-' then -1 * Decimal(Replace(t.OTHER_INSURANCE_ALLOWABLE,'-',''),12,2) else Decimal(t.OTHER_INSURANCE_ALLOWABLE,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.OTHER_INSURANCE_ALLOWABLE),
--Case when claims.ISDecimalCheck(t.OTHER_INSURANCE_DISCOUNT)=0 then 0 else Case when substr(rtrim(ltrim(t.OTHER_INSURANCE_DISCOUNT)),1,1)='-' then -1 * Decimal(Replace(t.OTHER_INSURANCE_DISCOUNT,'-',''),12,2) else Decimal(t.OTHER_INSURANCE_DISCOUNT,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.OTHER_INSURANCE_DISCOUNT),
t.BUNDLED_FOR_CES_EDITS,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
t.RPCSLINE_SORT,
t.RPCSSDRATE2,
t.OTHER_INSURANCE,
t.BCBS_DENY_CODE,
--Case when claims.ISDecimalCheck(t.DISCOUNT)=0 then 0 else Case when substr(rtrim(ltrim(t.DISCOUNT)),1,1)='-' then -1 * Decimal(Replace(t.DISCOUNT,'-',''),12,2) else Decimal(t.DISCOUNT,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.DISCOUNT),
t.DISCOUNT_CODE ,
--Case when claims.ISDecimalCheck(t.COPAY)=0 then 0 else Case when substr(rtrim(ltrim(t.COPAY)),1,1)='-' then -1 * Decimal(Replace(t.COPAY,'-',''),12,2) else Decimal(t.COPAY,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.COPAY),
--Case when claims.ISDecimalCheck(t.CARRIER_PAID)=0 then 0 else Case when substr(rtrim(ltrim(t.CARRIER_PAID)),1,1)='-' then -1 * Decimal(Replace(t.CARRIER_PAID,'-',''),12,2) else Decimal(t.CARRIER_PAID,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.CARRIER_PAID),
--Case when claims.ISDecimalCheck(t.CARRIER_DENIED)=0 then 0 else Case when substr(rtrim(ltrim(t.CARRIER_DENIED)),1,1)='-' then -1 * Decimal(Replace(t.CARRIER_DENIED,'-',''),12,2) else Decimal(t.CARRIER_DENIED,12,2) end end ,
dbo.ufn_Convert_to_Decimal(t.CARRIER_DENIED),
t.GROUPED ,
--Case when claims.ISDecimalCheck(t.LINE_NUMBER)=0 then 0 else Case when substr(rtrim(ltrim(t.LINE_NUMBER)),1,1)='-' then -1 * Decimal(Replace(t.LINE_NUMBER,'-',''),3,0) else Decimal(t.LINE_NUMBER,3,0) end end ,
dbo.ufn_Convert_to_Decimal(t.LINE_NUMBER),
--Case when claims.ISDecimalCheck(t.UNITS2)=0 then 0 else Case when substr(rtrim(ltrim(t.UNITS2)),1,1)='-' then -1 * Decimal(Replace(t.UNITS,'-',''),7,0) else Decimal(t.UNITS2,7,0) end end ,
dbo.ufn_Convert_to_Decimal(t.UNITS2),
t.DIAG_POINTER2, 
t.POST_PRICING_FLAG
from claims.dbo.MFELDOMCSCLMLINESNEW t;     

END TRY  
BEGIN CATCH  
   SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage;  
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;  

END CATCH; 

IF @@TRANCOUNT > 0  

    COMMIT TRANSACTION;  
  
END