-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[INSERT_MFELDOPENDEXCEPTIONS] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

BEGIN TRANSACTION; 

BEGIN TRY  

INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_1, t.pend_type_1, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_1 <> ''OR t.pend_type_1 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_2, t.pend_type_2, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_2 <> ''OR t.pend_type_2 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_3, t.pend_type_3, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_3 <> ''OR t.pend_type_3 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_4, t.pend_type_4, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_4 <> ''OR t.pend_type_4 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_5, t.pend_type_5, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_5 <> ''OR t.pend_type_5 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_6, t.pend_type_6, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_6 <> ''OR t.pend_type_6 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_7, t.pend_type_7, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_7 <> ''OR t.pend_type_7 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_8, t.pend_type_8, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_8 <> ''OR t.pend_type_8 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_9, t.pend_type_9, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_9 <> ''OR t.pend_type_9 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_10, t.pend_type_10, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_10 <> ''OR t.pend_type_10 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_11, t.pend_type_11, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_11 <> ''OR t.pend_type_11 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_12, t.pend_type_12, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_12 <> ''OR t.pend_type_12 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_13, t.pend_type_13, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_13 <> ''OR t.pend_type_13 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_14, t.pend_type_14, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_14 <> ''OR t.pend_type_14 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_15, t.pend_type_15, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_15 <> ''OR t.pend_type_15 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_16, t.pend_type_16, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_16 <> ''OR t.pend_type_16 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_17, t.pend_type_17, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_17 <> ''OR t.pend_type_17 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_18, t.pend_type_18, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_18 <> ''OR t.pend_type_18 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_19, t.pend_type_19, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_19 <> ''OR t.pend_type_19 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_20, t.pend_type_20, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_20 <> ''OR t.pend_type_20 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_21, t.pend_type_21, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_21 <> ''OR t.pend_type_21 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_22, t.pend_type_22, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_22 <> ''OR t.pend_type_22 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_23, t.pend_type_23, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_23 <> ''OR t.pend_type_23 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_24, t.pend_type_24, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_24 <> ''OR t.pend_type_24 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_25, t.pend_type_25, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_25 <> ''OR t.pend_type_25 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_26, t.pend_type_26, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_26 <> ''OR t.pend_type_26 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_27, t.pend_type_27, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_27 <> ''OR t.pend_type_27 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_28, t.pend_type_28, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_28 <> ''OR t.pend_type_28 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_29, t.pend_type_29, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_29 <> ''OR t.pend_type_29 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_30, t.pend_type_30, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_30 <> ''OR t.pend_type_30 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_31, t.pend_type_31, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_31 <> ''OR t.pend_type_31 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_32, t.pend_type_32, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_32 <> ''OR t.pend_type_32 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_33, t.pend_type_33, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_33 <> ''OR t.pend_type_33 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_34, t.pend_type_34, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_34 <> ''OR t.pend_type_34 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_35, t.pend_type_35, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_35 <> ''OR t.pend_type_35 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_36, t.pend_type_36, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_36 <> ''OR t.pend_type_36 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_37, t.pend_type_37, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_37 <> ''OR t.pend_type_37 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_38, t.pend_type_38, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_38 <> ''OR t.pend_type_38 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_39, t.pend_type_39, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_39 <> ''OR t.pend_type_39 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_40, t.pend_type_40, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_40 <> ''OR t.pend_type_40 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_41, t.pend_type_41, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_41 <> ''OR t.pend_type_41 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_42, t.pend_type_42, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_42 <> ''OR t.pend_type_42 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_43, t.pend_type_43, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_43 <> ''OR t.pend_type_43 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_44, t.pend_type_44, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_44 <> ''OR t.pend_type_44 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_45, t.pend_type_45, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_45 <> ''OR t.pend_type_45 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_46, t.pend_type_46, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_46 <> ''OR t.pend_type_46 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_47, t.pend_type_47, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_47 <> ''OR t.pend_type_47 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_48, t.pend_type_48, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_48 <> ''OR t.pend_type_48 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_49, t.pend_type_49, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_49 <> ''OR t.pend_type_49 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_50, t.pend_type_50, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_50 <> ''OR t.pend_type_50 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_51, t.pend_type_51, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_51 <> ''OR t.pend_type_51 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_52, t.pend_type_52, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_52 <> ''OR t.pend_type_52 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_53, t.pend_type_53, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_53 <> ''OR t.pend_type_53 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_54, t.pend_type_54, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_54 <> ''OR t.pend_type_54 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_55, t.pend_type_55, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_55 <> ''OR t.pend_type_55 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_56, t.pend_type_56, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_56 <> ''OR t.pend_type_56 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_57, t.pend_type_57, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_57 <> ''OR t.pend_type_57 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_58, t.pend_type_58, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_58 <> ''OR t.pend_type_58 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_59, t.pend_type_59, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_59 <> ''OR t.pend_type_59 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_60, t.pend_type_60, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_60 <> ''OR t.pend_type_60 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_61, t.pend_type_61, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_61 <> ''OR t.pend_type_61 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_62, t.pend_type_62, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_62 <> ''OR t.pend_type_62 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_63, t.pend_type_63, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_63 <> ''OR t.pend_type_63 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_64, t.pend_type_64, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_64 <> ''OR t.pend_type_64 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_65, t.pend_type_65, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_65 <> ''OR t.pend_type_65 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_66, t.pend_type_66, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_66 <> ''OR t.pend_type_66 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_67, t.pend_type_67, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_67 <> ''OR t.pend_type_67 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_68, t.pend_type_68, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_68 <> ''OR t.pend_type_68 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_69, t.pend_type_69, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_69 <> ''OR t.pend_type_69 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_70, t.pend_type_70, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_70 <> ''OR t.pend_type_70 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_71, t.pend_type_71, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_71 <> ''OR t.pend_type_71 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_72, t.pend_type_72, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_72 <> ''OR t.pend_type_72 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_73, t.pend_type_73, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_73 <> ''OR t.pend_type_73 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_74, t.pend_type_74, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_74 <> ''OR t.pend_type_74 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_75, t.pend_type_75, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_75 <> ''OR t.pend_type_75 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_76, t.pend_type_76, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_76 <> ''OR t.pend_type_76 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_77, t.pend_type_77, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_77 <> ''OR t.pend_type_77 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_78, t.pend_type_78, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_78 <> ''OR t.pend_type_78 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_79, t.pend_type_79, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_79 <> ''OR t.pend_type_79 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_80, t.pend_type_80, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_80 <> ''OR t.pend_type_80 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_81, t.pend_type_81, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_81 <> ''OR t.pend_type_81 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_82, t.pend_type_82, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_82 <> ''OR t.pend_type_82 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_83, t.pend_type_83, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_83 <> ''OR t.pend_type_83 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_84, t.pend_type_84, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_84 <> ''OR t.pend_type_84 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_85, t.pend_type_85, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_85 <> ''OR t.pend_type_85 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_86, t.pend_type_86, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_86 <> ''OR t.pend_type_86 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_87, t.pend_type_87, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_87 <> ''OR t.pend_type_87 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_88, t.pend_type_88, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_88 <> ''OR t.pend_type_88 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_89, t.pend_type_89, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_89 <> ''OR t.pend_type_89 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_90, t.pend_type_90, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_90 <> ''OR t.pend_type_90 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_91, t.pend_type_91, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_91 <> ''OR t.pend_type_91 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_92, t.pend_type_92, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_92 <> ''OR t.pend_type_92 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_93, t.pend_type_93, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_93 <> ''OR t.pend_type_93 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_94, t.pend_type_94, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_94 <> ''OR t.pend_type_94 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_95, t.pend_type_95, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_95 <> ''OR t.pend_type_95 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_96, t.pend_type_96, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_96 <> ''OR t.pend_type_96 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_97, t.pend_type_97, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_97 <> ''OR t.pend_type_97 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_98, t.pend_type_98, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_98 <> ''OR t.pend_type_98 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_99, t.pend_type_99, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_99 <> ''OR t.pend_type_99 <> ''
 INSERT INTO claims.dbo.eldopendexceptions  ( Policy_Underwriter, group_number, claim_number, mcs_claim_number, num_pended_reason, pended_reason_code, pend_type, hp_filler1)  SELECT t.Policy_Underwriter, t.group_number, t.claim_number, t.mcs_claim_number, t.num_pended_reason, t.pended_reason_code_100, t.pend_type_100, t.hp_filler1  FROM claims.dbo.mfeldopendexceptions  t where t.pended_reason_code_100 <> ''OR t.pend_type_100 <> ''

END TRY  
BEGIN CATCH  
   SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage;  
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;  

END CATCH; 

IF @@TRANCOUNT > 0  

    COMMIT TRANSACTION;  
  
END