-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[UPDATE_MFELDOMCSCLAIMSNEW] 

AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRANSACTION; 

DECLARE @cmd varchar(2000)
DECLARE @RECID as Integer
DECLARE @STARTTIME as DateTime
DECLARE @ENDTime as DateTime
DECLARE @RECCOUNT as Integer

insert into claims.dbo.LOADREPORTING values('1','MFELDOPAIDNEW_UPD','MFELDOPAIDNEW',0,0,0,'STARTED','',Getdate(),Getdate(),Current_Timestamp,null,0);

SELECT @RECID = IDENT_CURRENT ('LOADREPORTING') 

SET @STARTTIME = GetDate()

BEGIN TRY  

Update CLAIMS.DBO.MFELDOMCSCLAIMSNEW 
SET		FROM_DATE =	FORMAT(CONVERT(Date,CAST(IIF(ISDATE(FROM_DATE)=1,FROM_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		THRU_DATE =	FORMAT(CONVERT(Date,CAST(IIF(ISDATE(THRU_DATE)=1,THRU_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		DOB = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DOB)=1,DOB,'19000101') as Date), 101),'yyyyMMdd'),
		ADMIT_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(ADMIT_DATE)=1,ADMIT_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE1 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE1)=1,OCCUR_DATE1,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE2 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE2)=1,OCCUR_DATE2,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE3 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE3)=1,OCCUR_DATE3,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE4 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE4)=1,OCCUR_DATE4,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE5 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE5)=1,OCCUR_DATE5,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE6 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE6)=1,OCCUR_DATE6,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE7 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE7)=1,OCCUR_DATE7,'19000101') as Date), 101),'yyyyMMdd'),
		OCCUR_DATE8 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OCCUR_DATE8)=1,OCCUR_DATE8,'19000101') as Date), 101),'yyyyMMdd'),
		PRINC_PROC_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(PRINC_PROC_DATE)=1,PRINC_PROC_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_PROC_DATE1 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_PROC_DATE1)=1,OTHER_PROC_DATE1,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_PROC_DATE2 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_PROC_DATE2)=1,OTHER_PROC_DATE2,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_PROC_DATE3 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_PROC_DATE3)=1,OTHER_PROC_DATE3,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_PROC_DATE4 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_PROC_DATE4)=1,OTHER_PROC_DATE4,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_PROC_DATE5 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_PROC_DATE5)=1,OTHER_PROC_DATE5,'19000101') as Date), 101),'yyyyMMdd'),
		DATE_SIGNED1 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_SIGNED1)=1,DATE_SIGNED1,'19000101') as Date), 101),'yyyyMMdd'),
		OTHER_DOB = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(OTHER_DOB)=1,OTHER_DOB,'19000101') as Date), 101),'yyyyMMdd'),
		INSUR_DOB = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(INSUR_DOB)=1,INSUR_DOB,'19000101') as Date), 101),'yyyyMMdd'),
		DATE_SIGNED2 = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_SIGNED2)=1,DATE_SIGNED2,'19000101') as Date), 101),'yyyyMMdd'),
		DATE_NEXT_ACTION = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_NEXT_ACTION)=1,DATE_NEXT_ACTION,'19000101') as Date), 101),'yyyyMMdd'),
		DATE_RECEIVED = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_RECEIVED)=1,DATE_RECEIVED,'19000101') as Date), 101),'yyyyMMdd'),
		INVOICE_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(INVOICE_DATE)=1,INVOICE_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		ECS_OUTPUT_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(ECS_OUTPUT_DATE)=1,ECS_OUTPUT_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		HP_ADJUD_CREATED_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(HP_ADJUD_CREATED_DATE)=1,HP_ADJUD_CREATED_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		HP_ADJUD_CHANGED_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(HP_ADJUD_CHANGED_DATE)=1,HP_ADJUD_CHANGED_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		REVIEW_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(REVIEW_DATE)=1,REVIEW_DATE,'19000101') as Date), 101),'yyyyMMdd'),
		BENEFIT_PLAN_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(BENEFIT_PLAN_DATE)=1,BENEFIT_PLAN_DATE,'19000101') as Date), 101),'yyyyMMdd')

SET @RECCOUNT = @@ROWCOUNT 

END TRY  
BEGIN CATCH  
   SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage;  
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;  

	UPDATE claims.dbo.LOADREPORTING 
	SET STATUS = 'ERROR',
	ETIME = GetDate(),
	--MF_LOAD_COUNT = @@ROWCOUNT,
	DUR = datediff(MILLISECOND, @STARTTIME,@ENDTime),
	MF_LOAD_COUNT = (Select Count(*) FROM MFELDOPAIDNEW),
	STATUS_MESSAGE = ( SELECT   ERROR_NUMBER()  + ERROR_SEVERITY() + ERROR_STATE()+ ERROR_PROCEDURE() + ERROR_LINE() + ERROR_MESSAGE())
	WHERE REC_NUM = @RECID

END CATCH

IF @@TRANCOUNT > 0  
    COMMIT TRANSACTION;  

	UPDATE claims.dbo.LOADREPORTING 
	SET STATUS = 'COMPLETED',
	ETIME = GetDate(),
	--MF_LOAD_COUNT = @@ROWCOUNT,
	DUR = datediff(MILLISECOND, @STARTTIME,@ENDTime),
	MF_LOAD_COUNT = @RECCOUNT
	WHERE REC_NUM = @RECID
  
END