-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[UPDATE_MFELDOEMPLOYEENEW] 

AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY

BEGIN TRANSACTION; 

DECLARE @STARTTIME as DateTime
DECLARE @ENDTime as DateTime
DECLARE @RECCOUNT as Integer
DECLARE @RECID as Integer

Update claims.dbo.MFELDOEMPLOYEENEW 
SET DATE_LAST_CHANGED	= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_LAST_CHANGED)=1,DATE_LAST_CHANGED,'19000101') as Date), 101),'yyyyMMdd'),
DATE_OF_BIRTH			= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_OF_BIRTH)=1,DATE_OF_BIRTH,'19000101') as Date), 101),'yyyyMMdd'),
HIRED_DATE				= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(HIRED_DATE)=1,HIRED_DATE,'19000101') as Date), 101),'yyyyMMdd'),
DATE_OF_FIRST_ENROLLMENT = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(DATE_OF_FIRST_ENROLLMENT)=1,DATE_OF_FIRST_ENROLLMENT,'19000101') as Date), 101),'yyyyMMdd'),
LAST_BILLING_DATE		= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(LAST_BILLING_DATE)=1,LAST_BILLING_DATE,'19000101') as Date), 101),'yyyyMMdd'),
PREMIUMS_PAID_UNTIL		= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(PREMIUMS_PAID_UNTIL)=1,PREMIUMS_PAID_UNTIL,'19000101') as Date), 101),'yyyyMMdd'),
PCS_CARD_COMPLETE_DATE	= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(PCS_CARD_COMPLETE_DATE)=1,PCS_CARD_COMPLETE_DATE,'19000101') as Date), 101),'yyyyMMdd'),
ID_CARD_RUN_DATE		= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(ID_CARD_RUN_DATE)=1,ID_CARD_RUN_DATE,'19000101') as Date), 101),'yyyyMMdd'),
LABEL_RUN_DATE			= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(LABEL_RUN_DATE)=1,LABEL_RUN_DATE,'19000101') as Date), 101),'yyyyMMdd'),
CERTIFICATE_RUN_DATE	= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(CERTIFICATE_RUN_DATE)=1,CERTIFICATE_RUN_DATE,'19000101') as Date), 101),'yyyyMMdd'),
PD_THRU_DATE			= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(PD_THRU_DATE)=1,PD_THRU_DATE,'19000101') as Date), 101),'yyyyMMdd'),
HIPAA_CERTIFICATE_RUN_DATE = FORMAT(CONVERT(Date,CAST(IIF(ISDATE(HIPAA_CERTIFICATE_RUN_DATE)=1,HIPAA_CERTIFICATE_RUN_DATE,'19000101') as Date), 101),'yyyyMMdd'),
HCRA_EFF_DATE			= FORMAT(CONVERT(Date,CAST(IIF(ISDATE(HCRA_EFF_DATE)=1,HCRA_EFF_DATE,'19000101') as Date), 101),'yyyyMMdd')


END TRY  
BEGIN CATCH  
   SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage;  
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;  

	UPDATE claims.dbo.LOADREPORTING 
	SET STATUS = 'ERROR',
	ETIME = GetDate(),
	--MF_LOAD_COUNT = @@ROWCOUNT,
	DUR = datediff(MILLISECOND, @STARTTIME,@ENDTime),
	MF_LOAD_COUNT = (Select Count(*) FROM MFELDOPAIDNEW),
	STATUS_MESSAGE = ( SELECT   ERROR_NUMBER()  + ERROR_SEVERITY() + ERROR_STATE()+ ERROR_PROCEDURE() + ERROR_LINE() + ERROR_MESSAGE())
	WHERE REC_NUM = @RECID

END CATCH

IF @@TRANCOUNT > 0  
    COMMIT TRANSACTION;  

	UPDATE claims.dbo.LOADREPORTING 
	SET STATUS = 'COMPLETED',
	ETIME = GetDate(),
	--MF_LOAD_COUNT = @@ROWCOUNT,
	DUR = datediff(MILLISECOND, @STARTTIME,@ENDTime),
	MF_LOAD_COUNT = @RECCOUNT
	WHERE REC_NUM = @RECID
  
END