ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\!!drao];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\SRV_SQL_WNYSQL73_UAT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\!!jpwelch];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\MSSQLSERVER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\drao];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\rmysore];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CLAIMS_USER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ALICO\!!KGundapaneni];


GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [ALICO\drao];

